aws/aws-node-termination-handler

- README.md
> fix kubernetes yaml url

- BUILD.md
- Dockerfile
- node-termination-handler.yaml
*Issue #, if available:* 
https://github.com/aws/aws-node-termination-handler/issues/3
Use kube-system instead of default
> Use kube-system 

- config/base/cluster-role.yaml
*Issue #10*
Restricting RBAC rules down to only those required. 
> Restricting RBAC rules

- .travis.yml
- Makefile
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/spot-termination-test/run-spot-termination-test.sh
> travis build multi-stage matrix build

- handler.go
*Issue #21*
Added retry logic to instance metadata request. Pods now make up to 3 retries before restarting the pod. 
> Add retry logic to metadata request

- .travis.yml
https://github.com/aws/aws-node-termination-handler/issues/25
deploy on tagged push
> update build to deploy releases

- .travis.yml
- Dockerfile
- Makefile
- scripts/build-binaries
- scripts/sync-readme-to-dockerhub
- scripts/upload-binaries-to-github
- test/license-test/run-license-test.sh
- Build multiple platform binaries with the docker image 
- Upload built platform binaries to github release assets upon tag push
- Sync github readme with dockerhub full_description
> setup release scripts

- scripts/sync-readme-to-dockerhub
Fix env var for dockerhub password
> sync-readme-to-dockerhub: fix env variable for dockerhub password

- .github/PULL_REQUEST_TEMPLATE.md
Issue #56
We should match the language used in other AWS repos, which states that
the contribution is made under Apache 2.0 license terms.
> update PR template with APL2.0 language

- pkg/drainevent/drain-event_test.go
```
PASS
coverage: 100.0% of statements
ok      github.com/aws/aws-node-termination-handler/pkg/drainevent    1.166s
```
> Add drain-event unit test

- test/helm-sync-test/run-helm-sync-test
N/A
Enhance the helm-sync-test to also look at PRs in eks-charts to make our tests fail less often :) 
> helm-sync-test: look at PRs too

- cmd/node-termination-handler.go
- pkg/drainevent/scheduled-event.go
- pkg/drainevent/spot-itn-event.go
N/A
This is a cleanup and slight restructure of the monitor loops for drain events. This pulls out the for loops into the main cmd so that the monitor call can propagate errors up.  It also more clearly shows the monitor looping interval and will make adding unit tests easier. 
- Removed logging an error on IMDS 404 for SPOT ITN since this is a proper response from that API. If no spot interruption exists, a 404 is sent. 
---
> monitor functions return errs and loop in main

- test/k8s-local-cluster-test/provision-cluster
N/A
Update KinD to the latest and greatest v0.7.0
---
> update kind and node images to v0.7.0

- .travis.yml
- Makefile
> Run unit tests in travis build

- pkg/draineventstore/drain-event-store.go
- pkg/draineventstore/drain-event-store_test.go
The drain event store was implemented with an ignore drain event by using the Drained flag on the event itself. However, there is an edge case as follows:
1. Event 123 is ignored on startup due to a labeled node coming back from a scheduled reboot and is therefore added to the drain store with Drained=true
2. Another scheduled maintenance drain event is added to the store which is not ignored
3. The maintenance window opens for the event, and the node has been drained
4. The event is cancelled and the Event 123 which has been ignored has not yet flipped to a completed state (which would cancel the event and evict it from the data store)
5. The node should uncordon itself, but it …
> draineventstore: use separate ignored event hashset and tests

- pkg/drainevent/scheduled-event.go
- pkg/drainevent/scheduled-event_internal_test.go
- pkg/drainevent/scheduled-event_test.go
- pkg/drainevent/spot-itn-event_test.go
- pkg/node/node.go
> Adding scheduled event unit tests

- README.md
https://github.com/aws/aws-node-termination-handler/issues/74
Updating readme to mention requirement of metadata access to function.
> add installation requirement of metadata access

- pkg/config/config.go
- pkg/config/config_internal_test.go
- pkg/config/config_test.go
N/A
Revert the refactor to err recover on env var panic and return err to calling code.  
> config fixes to cli and tests

- config/helm/aws-node-termination-handler/README.md
> update helm readme with webhooks

- go.sum
- pkg/config/config.go
- pkg/drainevent/scheduled-event_internal_test.go
- pkg/node/node.go
- pkg/node/node_internal_test.go
- pkg/node/node_test.go
Added unit tests for node.go and scheduled-event.go
> Adding tests for node.go

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
Enable PSP and associated resources by default in helm chart. 
> enable psp by default in helm chart

- test/e2e/webhook-test
n/a
updating the webhook template for integration tests as i've changed the travis secrets so we can more easily monitor the test run results
> updating webhook template for integration tests

- cmd/node-termination-handler.go
- pkg/drainevent/scheduled-event.go
- pkg/drainevent/spot-itn-event.go
- pkg/draineventstore/drain-event-store.go
- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_test.go
- pkg/node/node.go
- pkg/webhook/webhook_test.go
Variable and comment changes to fix misspellings and non-idiomatic syntax. 
This is the second revision to #108 which I accidentally closed when squashing my changes prematurely 🙃
> Variable naming and comment fixes

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
update chart version and docker img version for 1.3.0 release
> update chart version and docker img version

- .travis.yml
- Makefile
- test/helm-sync-test/run-helm-version-sync-test
N/A
Add test to check if helm app version in the Chart and default values.yaml tag is in-sync w/ the latest release tag.
> helm version sync test

- .travis.yml
- Dockerfile
- README.md
- go.mod
N/A
update go from 1.13 to 1.14
> update to go 1.14

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
https://github.com/aws/aws-node-termination-handler/issues/121
- Increment chart patch version
- Increment app patch version to v1.3.1 of NTH
- Increment tag version to v1.3.1 of NTH
> update chart for v1.3.1 patch

- Makefile
> Adding login prompt to push-docker-images in Makefile

- config/helm/aws-node-termination-handler/templates/daemonset.yaml
N/A
- Support arm/arm64 cpu architectures within kubernetes
> support arm and arm64 architectures

- THIRD_PARTY_LICENSES
N/A 
Adding project header to the THIRD_PARTY_LICENSES file. 
> Add header to THIRD_PARTY_LICENSES file

- cmd/node-termination-handler.go
- pkg/drainevent/scheduled-event.go
- pkg/node/node.go
Found some small issues when working on another pr, addressing these in this pr. The only slightly significant change is catching the error from calling drain and logging it then exiting. 
> Logging, comment, and style fixes

- .travis.yml
- config/helm/aws-node-termination-handler/Chart.yaml
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
> update kind and helm for e2e tests

- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/values.yaml
> Replace deprecated values

- README.md
N/A
Update install instructions to use latest so we don't have to increment it when we release new versions.
> readme update for installation instructions

- README.md
N/A 
Github doesn't support the "latest" tag on download links :( 
> Update installation cmd in README

- .travis.yml
N/A
Travis should run license test on tag releases too. 
> update travis to run license test on tag releases

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
Update helm chart version and app version for v1.5.0 release
eks-charts sync PR: https://github.com/aws/eks-charts/pull/183
> prepare for 1.5.0 release

- .travis.yml
N/A
- fixed missing script to sync readme to dockerhub
> fix docker sync readme

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
This PR adds a new `podLabels` parameter, to the Helm Chart,  which allows setting extra labels to each pod.
> [helm chart] Add new podLabels parameter for adding labels to each pod

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
> prepare for v1.6.0 release

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
Upping helm app versions for pending patch release
> up for patch release

- .travis.yml
- Makefile
- scripts/run-unit-tests-in-docker
- test/eks-cluster-test/run-test
- test/go-report-card-test/run-report-card-test.sh
- test/k8s-local-cluster-test/provision-cluster
- test/readme-test/run-readme-spellcheck
- test/readme-test/spellcheck-Dockerfile
- test/shellcheck/run-shellcheck
N/A
- Add Shellcheck to check for errors in bash files
- Fix errors found in bash files
- Add spellcheck to check markdown files
- Fix spelling errors in markdown files
> add shellcheck and spellcheck

- Makefile
- scripts/build-binaries
N/A
- Generate tar.gz bin files for more efficient downloads and for use as static bottles for homebrew.
- Generate .zip bin file for windows
> build .tar.gz bin files

- config/helm/aws-node-termination-handler/Chart.yaml
- bump chart version due to #209 
> bump chart.yaml version

- BUILD.md
- Dockerfile
- config/helm/aws-node-termination-handler/README.md
- config/helm/squid/templates/daemonset.yaml
- config/helm/squid/values.yaml
- pkg/ec2metadata/ec2metadata_test.go
- scripts/generate-k8s-yaml
- scripts/push-docker-images
- scripts/sync-readme-to-dockerhub
- scripts/upload-resources-to-github
- test/e2e/imds-v2-test
- test/e2e/webhook-http-proxy-test
- test/eks-cluster-test/run-test
- test/helm-sync-test/run-helm-sync-test
- test/helm/helm-lint
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/delete-cluster
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
- test/license-test/Dockerfile
- test/license-test/gen-license-report.sh
- test/license-test/license-config.hcl
- test/webhook-test-proxy/Dockerfile
Issue #163
**Description**
* fix NTH log output on failure in local suite
* add NTH log output on failure to EKS suite
* remove trailing whitespace
> Fix log output on e2e tests when a failure occurs (#163)

- test/README.md
Description of changes: 
* Adding readme to demystify e2e tests
> add readme for e2e tests

- config/helm/aws-node-termination-handler/values.yaml
- config/helm/webhook-test-proxy/values.yaml
Issue #220 
**Description**
Add properties referenced in Helm chart templates to values.yaml.
> add missing helm chart properties (#220)

- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
https://github.com/aws/aws-node-termination-handler/issues/226
fix missing new line for updateStrategy
> fix missing new line for updateStrategy

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/values.yaml
#226 
bumping version for helm chart release
> bumping version for helm chart release

- config/helm/aws-node-termination-handler/test.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- test/helm/helm-lint
N/a
- add helm test to check template generation
- sync enableSpotInterruption usage statement
> Helm Template Gen Test

- .travis.yml
> Update .travis.yml go1.15

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
n/a
up helm chart version and app version for v.1.7.0 release
> up helm chart to use v1.7.0 image

- test/e2e/cordon-only-test
- test/e2e/imds-v2-test
- test/e2e/maintenance-event-cancellation-test
- test/e2e/maintenance-event-dry-run-test
- test/e2e/maintenance-event-reboot-test
- test/e2e/maintenance-event-test
- test/e2e/prometheus-metrics-test
- test/e2e/spot-interruption-dry-run-test
- test/e2e/spot-interruption-test
- test/e2e/webhook-http-proxy-test
- test/e2e/webhook-secret-test
- test/e2e/webhook-test
- test/eks-cluster-test/run-test
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
N/A
- Add retry to AEMM helm install to get around github throttling. 
- Add podMonitor creation to prometheus e2e test
> retry aemm installs

- scripts/upload-resources-to-github
N/A
- Fix github upload script typo.
> fix release script upload to github

- test/e2e/maintenance-event-reboot-test
- test/eks-cluster-test/run-test
- test/k8s-local-cluster-test/run-test
* upgrade aemm to 1.6
Testing:
* `make e2e-test` locally
> upgrade aemm to 1.6

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
none
Increase Helm version for next release
> Bump Helm chart version for 1.8 release

- test/go-report-card-test/Dockerfile
> fix go-report-card test

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
- increment helm app and chart version for nth release v1.9.0
> up helm app and chart versions for v1.9.0

- config/helm/aws-node-termination-handler/README.md
- pkg/config/config.go
N/A
Update default webhook template to include the instance id
> Update default webhook

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/psp.yaml
- config/helm/aws-node-termination-handler/values.yaml
- scripts/generate-k8s-yaml
- scripts/upload-resources-to-github
- test/e2e/spot-interruption-test-host-networking-off
N/A
- Make host networking optional
The original PR was opened under eks-chart by Leo Palmer Sunmo @leosunmo . That one needed to be closed out so we can run the full e2e tests in this repo before syncing to eks-charts. Thanks @leosunmo !!
> make host networking optional

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
* N/A
* Bumping helm versions
* Will update the same in eks-charts post-release
> bump helm app and chart versions to v1.10.0

- test/helm-sync-test/run-helm-sync-test
N/A
Fix helm sync check w/ eks-charts since one of the PR's fork is deleted which caused the check to crash. 
> fix helm sync script

- README.md
N/A
* aligning version numbers with latest
> Bump version numbers in installations

- config/helm/aws-node-termination-handler/README.md
- test/e2e/asg-lifecycle-sqs-test
- test/e2e/ec2-state-change-sqs-test
- test/e2e/rebalance-recommendation-sqs-test
- test/e2e/spot-interruption-sqs-test
N/A
* AEMM and overriding instance metadata URL not needed for sqs tests --> removed
* Helm ReadMe zero-config instructs return an error for me (-- name does not exist) --> correcting it and now it aligns with main ReadMe
> Minor fixes

- pkg/ec2metadata/ec2metadata.go
* #277 
* Reduce connection timeout to `2 sec`
* If there are issues querying IMDS (specifically `/latest/dynamic/instance-identity/document`) on startup, then do **not** continue to query IMDS
Testing:
* Before changes, NTH would take 40+ sec to startup if calls to IMDS were failing
* Tested on local cluster:
* `metadataTries=0` -->  2sec startup
* `metadataTries=3` (default) -->  11sec startup
> reduce imds retries on error

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.11.0 release. Updating release versions in repo.
> 🥑🤖 v1.11.0 release prep

- config/helm/aws-node-termination-handler/Chart.yaml
> Update Chart version

- .github/workflows/ci.yml
- test/go-report-card-test/run-report-card-test.sh
N/A
Move from Travis to Github Actions!
> add github actions workflow file

- README.md
https://github.com/aws/aws-node-termination-handler/issues/305
Add docs on how the feature flag config keys behave for IMDS Processing mode and Queue Processor Mode. 
> Update README w/ docs on feature flag config keys

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.11.1 release. Updating release versions in repo.
> 🥑🤖 v1.11.1 release prep

- README.md
> Increment versions

- Makefile
N/A
- Fix dockerlogin for gh actions
> fix docker login for gh actions

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.11.2 release. Updating release versions in repo.
> 🥑🤖 v1.11.2 release prep

- .github/workflows/ci.yml
N/A
ECR publishing needs creds
> add secrets for ecr publishing

- .github/workflows/ci.yml
- scripts/sync-readme-to-dockerhub
N/A
Fix docker env var naming issue
> fix docker creds issues

- Makefile
N/A
- Copy-Paste error on windows push image make target
> fix copy-paste issue for windows image push

- README.md
> Bump versions

- Makefile
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/values.yaml
N/A
- Update ECR registry with alias
> update ecr registry with alias

- go.mod
> ran go mod tidy

- CONTRIBUTING.md
N/A
A CLA will not be required to contribute
> remove cla

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.12.1 release. Updating release versions in repo.
> 🥑🤖 v1.12.1 release prep

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.12.2 release. Updating release versions in repo.
> 🥑🤖 v1.12.2 release prep

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.13.0 release. Updating release versions in repo.
> 🥑🤖 v1.13.0 release prep

- config/helm/aws-node-termination-handler/templates/psp.yaml
https://github.com/aws/aws-node-termination-handler/issues/417
- Change the ClusterRole to a namespace scoped role and move RoleBinding to proper namespace reference.
> fix psp role

- config/helm/aws-node-termination-handler/templates/psp.yaml
https://github.com/aws/aws-node-termination-handler/issues/441
- Fix RoleBinding Kind to match Role type 
> fix rolebinding kind

- scripts/draft-release-notes
N/A
- Removed xargs pipe since it's unnecessary and causes issues when a commit message has an apostrophe (single quote). 
> fix draft-release-notes issue w/ single quotes

- .github/workflows/ci.yml
- README.md
- test/eks-cluster-test/cluster-spec.yaml
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
N/A
- Update kind binary, associated images, and versions of k8s tested
- Update helm to latest binary
> update helm and kind

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.13.1 release. Updating release versions in repo.
> 🥑🤖 v1.13.1 release prep

- .github/workflows/ci.yml
Adding aws creds to GitHub Actions file. These are used for uploading images to ecr public
> Add aws credentials to github actions

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
The chart was missing the actual livenessProbe, even though it was defined in the values.
> fix(chart): added missing livenessProbe

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.13.2 release. Updating release versions in repo.
> 🥑🤖 v1.13.2 release prep

- .github/workflows/ci.yml
> remove session token

- config/helm/aws-node-termination-handler/templates/clusterrole.yaml
- test/e2e/emit-events-test
- test/k8s-local-cluster-test/run-test
https://github.com/aws/aws-node-termination-handler/issues/477
- Add events Patch permission
- Add k8s event emission test
> fix k8s event patch permission and add test

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/values.yaml
🥑🤖 Auto-generated PR for v1.13.3 release. Updating release versions in repo.
> 🥑🤖 v1.13.3 release prep

- README.md
n/a
- Add announcement to readme for feedback on community meeting interest.
> Add community meeting announcement to readme

- config/helm/aws-node-termination-handler/values.yaml
Fixing typo error in helm chart values
> Fixing typo

- README.md
Issue #, if available: https://github.com/aws/aws-node-termination-handler/discussions/523
* Adds community meeting date, time, and location
> Add community meeting details

- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/templates/pdb.yaml
- config/helm/aws-node-termination-handler/templates/podmonitor.yaml
- config/helm/aws-node-termination-handler/templates/psp.yaml
- config/helm/aws-node-termination-handler/templates/service.yaml
- config/helm/aws-node-termination-handler/templates/serviceaccount.yaml
- config/helm/aws-node-termination-handler/templates/servicemonitor.yaml
**Description of changes**:
This PR explicitly adds the `namespace` the the metadata of all namespace scoped resources. It also fixes the `PodSecurityPolicy` for Linux DaemonSets.
> feat[chart]: Add namespace to metadata

- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.15.0 release. Updating release versions in repo.
> 🥑🤖 v1.15.0 release prep

- .github/PULL_REQUEST_TEMPLATE.md
Description of changes: Making the headers bold (and brash) so information is more readable by default
^^ will become:
**Description of changes:** Making the headers bold (and brash) so information is more readable
> Bold the headers in pull request template

- README.md
**Issue #, if available:** #526
Add a note in the README about encrypted SQS queues.
> Add a note related to encrypted SQS queues

- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.16.1 release. Updating release versions in repo.
> 🥑🤖 v1.16.1 release prep

- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.16.2 release. Updating release versions in repo.
> 🥑🤖 v1.16.2 release prep

- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.16.3 release. Updating release versions in repo.
> 🥑🤖 v1.16.3 release prep

- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.16.4 release. Updating release versions in repo.
> 🥑🤖 v1.16.4 release prep

- .github/workflows/build-and-test.yaml
**Issue #, if available:** N/A, we experience transient failures running early AM so experimenting with a more "active" time
> Update daily runs to afternoon

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.17.0 release. Updating release versions in repo.
> 🥑🤖 v1.17.0 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.17.1 release. Updating release versions in repo.
> 🥑🤖 v1.17.1 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.17.2 release. Updating release versions in repo.
> 🥑🤖 v1.17.2 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.17.3 release. Updating release versions in repo.
> 🥑🤖 v1.17.3 release prep

- Makefile
Update Make invocation of `prepare-for-release.sh` to add download location of `gum` to PATH.
> add downloaded binaries to PATH

- Makefile
- scripts/download-gh.sh
- scripts/sync-to-aws-eks-charts.sh
Added script that creates a PR to aws/eks-charts with the latest NTHv2 helm chart.
> add sync-to-aws-eks-charts.sh script

- scripts/build-and-push-images.sh
- scripts/sync-readme-to-ecr-public.sh
Update script to handle undefined environment variable rather than terminating with an error.
> handle undefined variable in release scripts

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.18.0 release. Updating release versions in repo.
> 🥑🤖 v1.18.0 release prep

- go.mod
- go.sum
Gradually upgrading some of our dependencies:
* prometheus/client_golang
* golang.org/x/crypto
* aws-sdk-go v1
> Upgrade some dependencies

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.18.1 release. Updating release versions in repo.
> 🥑🤖 v1.18.1 release prep

- README.md
- charts/aws-node-termination-handler-2/Chart.yaml
- charts/aws-node-termination-handler-2/values.yaml
🥑🤖 Auto-generated PR for v2.0.0-beta release. Updating release versions in repo.
> 🥑🤖 v2.0.0-beta release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.18.2 release. Updating release versions in repo.
> 🥑🤖 v1.18.2 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.18.3 release. Updating release versions in repo.
> 🥑🤖 v1.18.3 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.19.0 release. Updating release versions in repo.
> 🥑🤖 v1.19.0 release prep

- .github/workflows/build-and-test.yaml
- .github/workflows/release.yaml
Fixing broken checks related to windows - https://github.com/aws/aws-node-termination-handler/actions/runs/5281531474/jobs/9557601385?pr=839 due to a [recently released version of chocolatey](https://github.com/chocolatey/choco/releases/tag/2.0.0).
> fix windows builds

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.20.0 release. Updating release versions in repo.
> 🥑🤖 v1.20.0 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
Reverts aws/aws-node-termination-handler#839
> Revert "🥑🤖 v1.20.0 release prep"

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.21.0 release. Updating release versions in repo.
> 🥑🤖 v1.21.0 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
Reverted previous release prep (commit f3b7d4fd0a150fa0179f32d6ef0ee754d32625d8).
> Revert "🥑🤖 v1.21.0 release prep 🤖🥑 (#953)"

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
Reverted release prep (commit 519c0caaf469b29fa9e4553270acfb740df2abd6).
> Revert "🥑🤖 v1.21.0 release prep (#962)"

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.22.0 release. Updating release versions in repo.
> 🥑🤖 v1.22.0 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
Reverted release prep (commit 9e5915b4aaad72be008b8f4e4a3131860b9eef2a)
> Revert 🥑🤖 v1.22.0 release prep (#1002)

- .github/workflows/build-and-test.yaml
- README.md
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
* added `1.30` tests
I  use #986 to create same approach update to cover `1.30`
> feat: Add k8s 1.30 to test versions

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.22.1 release. Updating release versions in repo.
> 🥑🤖 v1.22.1 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
This reverts commit be76a1881dcc6e7289e50bc3873f6275e7643f07.
Windows assets still not getting updated and caused release failure, so reverting the release.
> Revert "🥑🤖 v1.22.1 release prep (#1044)"

- .github/workflows/build-and-test.yaml
- pkg/monitor/sqsevent/sqs-monitor.go
**Issue #, if available:** Lint test failures in recent PR's and CI/CD failure.
- Made changes to fix the lint failures.
- Modified the version in build-and-test yaml file to use the latest version.
> For testing the lint failures

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.23.0 release. Updating release versions in repo.
> 🥑🤖 v1.23.0 release prep

- pkg/config/config.go
#1100
set enableASGLifecycleDraining default to false
None 
> set enableASGLifecycleDrainingDefault to false

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.23.1 release. Updating release versions in repo.
> 🥑🤖 v1.23.1 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.24.0 release. Updating release versions in repo.
> 🥑🤖 v1.24.0 release prep

- .github/workflows/build-and-test.yaml
- Makefile
- README.md
- scripts/generate-k8s-yaml
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
#1127
Add k8s 1.32 support
Kubernetes Version: 1.32
Test in local by `make compatibility-test`
> Add k8s 1.32 support

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.24.1 release. Updating release versions in repo.
> 🥑🤖 v1.24.1 release prep

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
This reverts commit 03a3278e52c49d49299f01ac33a321d4e47b823a.
> Revert "🥑🤖 v1.24.1 release prep (#1138)"

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.25.0 release. Updating release versions in repo.
> 🥑🤖 v1.25.0 release prep

- .github/ISSUE_TEMPLATE/bug_report.md
Adding consistent whitespaces in bug report template. Made me a bit crazy when writing issues.
Environment (Linux / Windows): 
Kubernetes Version: 
> Add consistent whitespaces in bug report template

- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.25.1 release. Updating release versions in repo.
> 🥑🤖 v1.25.1 release prep

- README.md
**Issue #, if available:** [1182](https://github.com/aws/aws-node-termination-handler/issues/1182)
- Updated readme to include windows 2019 deprecation notice.
Environment (Linux / Windows): 
Kubernetes Version: 
> Update readme to add windows 2019 deprecation notice
