- node-termination-handler.yaml
DaemonSet, Deployment, and ReplicaSet resources will no longer be served from extensions/v1beta1, apps/v1beta1, or apps/v1beta2 in v1.16. Migrate to the apps/v1 API, available since v1.9. Existing persisted data can be retrieved via the apps/v1 API.
> Migrate DaemonSet API

- BUILD.md
- Dockerfile
- README.md
- Split module download which makes build faster in case `go.mod` remains unchanged
- Adjusted Dockerfile to be multi-target ready and added multi-target build into README.
> create multi-target build

- README.md
https://github.com/aws/aws-node-termination-handler/issues/4
README updates to explain how to setup a node-selector for spot instances without maintaining a completely custom kubernetes resource file. 
> docs update about setting up a node selector for spot instances

- README.md
- handler.go
https://github.com/aws/aws-node-termination-handler/issues/20
https://github.com/aws/aws-node-termination-handler/issues/11
Most everything is configurable via env vars and CLI arg overrides. We also have Helm support now that will allow you to helm install with args to override the env vars introduced in this PR. 
> implement more configuration through env vars and cli override args

- Makefile
https://github.com/aws/aws-node-termination-handler/issues/25
- Added git tag versioning to makefile
- added test targets in makefile
If this PR is accepted I'll do a git annotated tag v1.0.0 release on this commit. 
> update makefile to support versioning w/ git tags and tests

- Makefile
- test/go-report-card-test/Dockerfile
- test/go-report-card-test/run-report-card-test.sh
N/A
- Add `fmt` target to Makefile which uses go imports to fmt go source files
- Add goimports to go-report-card test 
> integrate goimports into makefile and go-report-card test

- cmd/node-termination-handler.go
- pkg/config/config.go
- pkg/drainer/drainer.go
- pkg/ec2metadata/ec2metadata.go
https://github.com/aws/aws-node-termination-handler/issues/29
This change adds a configurable nodeTerminationGracePeriod which specifies how long a node is given to drain. This information is used within the drain logic to respond to scheduled drainable events (like spot interruption termination notice) so that every second of compute can be squeezed out of the node before a drain is initiated. The default value is 2 minutes which is the default spot ITN period. 
This also changes the configurable grace-period to pod-termination-grace-period to better differentiate the two configurable grace-periods. This code will be released in the v2.0.0 release since it breaks the backwards compatible configuration. 
If the new config changes are …
> node-termination-grace-period configuration option added

- pkg/config/config.go
If an environment variable is specified but no value is present, fallback to the default value. 
> use default values if env var is specified but empty

- config/helm/ec2-metadata-test-proxy/.helmignore
- config/helm/ec2-metadata-test-proxy/Chart.yaml
- config/helm/ec2-metadata-test-proxy/templates/daemonset.yaml
- config/helm/ec2-metadata-test-proxy/templates/regular-pod-test.yaml
- config/helm/ec2-metadata-test-proxy/templates/service.yaml
- config/helm/ec2-metadata-test-proxy/values.yaml
- Add an ec2-metadata-test-proxy helm chart so we can make the tests a bit smaller by getting rid of kustomize heredocs
> add ec2-metadata-test-proxy helm chart

- cmd/node-termination-handler.go
- pkg/drainevent/drain-event.go
- pkg/drainevent/spot-itn-event.go
- pkg/ec2metadata/ec2metadata.go
N/A
- Refactor the event handling logic to be have more generic event handling that does not need to be touched when adding an additional drainable event.
- This PR adds a go routine which blocks on a go channel to receive drain events from monitor loop sources. The only monitor loop involved right now is the spot ITN loop. As more events types are introduced, the developer simply needs to write a monitor loop that uses the function interface and provide the function to the list of monitor functions.
> use channels to coordinate drainable events

- .github/stale.yml
Configured bot to mark PRs stale after 7 days and close them 3 days later
> Adding in probot-stale configuration

- .travis.yml
- test/k8s-local-cluster-test/provision-cluster
N/A
- upgrade kind to version v0.6.1
- quiet the cluster creation animation since it doesn't display well on travis logs
- use new kind docker node images
- pull out curl to k8s stable.txt file to the top of the provision script to live with the rest of the version variables
- add k8s 1.17 node image and include in travis test matrix
> upgrade kind to v0.6.1 and add k8s 1.17

- Makefile
- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/drainevent/drain-event.go
- pkg/draineventstore/drain-event-store.go
- pkg/draineventstore/spot-itn-event.go
- pkg/webhook/webhook.go
- test/e2e/webhook-test
- test/ec2-metadata-test-proxy/cmd/ec2-metadata-test-proxy.go
Implemented webhook functionality, ability to specify message template and custom headers for each provider, includes integration tests
#5 
Sorry about the delay in getting this out, but this should now address issue 5 pretty well.  You have the ability to include arbitrary headers and message format, I've tested against Amazon Chime and Slack both seem to work just fine.  In a future PR I plan to add additional information available to the template.
> Implemented webhook functionality

- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/templates/serviceaccount.yaml
When rendering out the helm chart to template files, the generated manifests don't have namespaces for all the namespaced resources. This fix adds the missing `namespace` to the `DaemonSet` and `ServiceAccount` resources.
> Added missing namespace references to helm chart

- cmd/node-termination-handler.go
- config/helm/ec2-metadata-test-proxy/templates/daemonset.yaml
- config/helm/ec2-metadata-test-proxy/values.yaml
- pkg/draineventstore/drain-event-store.go
- pkg/draineventstore/scheduled-event.go
- pkg/draineventstore/spot-itn-event.go
- pkg/node/node.go
- test/e2e/maintenance-event-cancellation-test
- test/ec2-metadata-test-proxy/cmd/ec2-metadata-test-proxy.go
This PR implements a cancel drain event channel and handler function. The new cancel drain channel is passed to all monitor functions. The Monitor functions are responsible for the cancellation logic for each specific case.  The Spot ITN monitoring function accepts the cancel channel as an argument but ignores it since there is never a case where we should cancel a spot ITN drain event. Scheduled maintenance events are able to be cancelled, either by the AWS user or by EC2. The monitor loop will watch for status changes in the metadata response for maintenance events and propagate those to the cancel channel. 
Once a cancel event is received, the root cancel handler will query the drain event store data …
> implement cancellation of drain events

- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_internal_test.go
- pkg/ec2metadata/ec2metadata_test.go
- pkg/test/helpers.go
```
2020/01/20 15:52:34 Request failed. Attempts remaining: 2
2020/01/20 15:52:34 Sleep for 1.205µs seconds
2020/01/20 15:52:34 Request failed. Attempts remaining: 1
2020/01/20 15:52:34 Sleep for 2.71µs seconds
PASS
coverage: 100.0% of statements
ok      github.com/aws/aws-node-termination-handler/pkg/ec2metadata    1.366s
```
> Adding unit tests for ec2metadata package

- pkg/webhook/webhook_test.go
unit tests for webhook
Output
```
2020/01/21 15:59:48 Webhook Success: Notification Sent!
2020/01/21 15:59:48 Webhook Error: Template parsing failed - template: message:1: unexpected unclosed action in command
2020/01/21 15:59:48 Webhook Error: Template execution failed - template: message:1:2: executing "message" at <.cat>: can't evaluate field cat in type *drainevent.DrainEvent
2020/01/21 15:59:48 Webhook Error: Http NewRequest failed - parse     : net/url: invalid control character in URL
2020/01/21 15:59:48 Webhook Error: Header Unmarshal failed - unexpected end of JSON input
2020/01/21 15:59:53 Webhook Error: Client Do failed - Post http://127.0.0.1:60999: net/http: request canceled (Client.Timeout exceeded while awaiting headers) …
```
> Adding webhook unit tests

- pkg/draineventstore/drain-event-store.go
- pkg/draineventstore/drain-event-store_test.go
```
PASS
coverage: 44.3% of statements
ok  	github.com/aws/aws-node-termination-handler/pkg/draineventstore	1.217s
```
* There is 100% coverage for the drain-event-store.go file, but the 44.3% is for the entire draineventstore package
> Adding drain-event-store tests

- config/helm/aws-node-termination-handler/values.yaml
- test/e2e/maintenance-event-cancellation-test
- test/e2e/maintenance-event-dry-run-test
- test/e2e/maintenance-event-test
- test/e2e/spot-interruption-dry-run-test
- test/e2e/spot-interruption-test
- test/e2e/webhook-test
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
N/A
e2e tests in travis have been intermittently failing. This PR fixes some stability issues with the tests and removes some code that can be placed in the base `run-test` script.  I tested these on my fork w/ travis and tests completed successfully several times in a row. 
> fix e2e test stability issues

- test/e2e/webhook-test
N/A
Fix the webhook test on git push. This test should use the travis secret to post to an actual messaging app to test webhook delivery. The shell conditional was always evaluating to true. 
> fix webhook test on push

- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/drainevent/drain-event.go
- pkg/drainevent/scheduled-event.go
- pkg/drainevent/spot-itn-event.go
- pkg/node/node.go
- pkg/webhook/webhook.go
- test/e2e/maintenance-event-reboot-test
- test/k8s-local-cluster-test/run-test
This change supports labeling the current node with an action tag and action-time tag in order to support uncordoning the node after a maintenance event requiring a reboot.  This automates the process of cordoning nodes temporarily going down for maintenance and then removing the cordon when the maintenance has been completed. 
- If a `system-reboot` maintenance event is received, the scheduled-maintenance-event monitor loop will add a new `PreDrainTask` to the `drainevent` which is a function that executes right before the node is cordoned and drained. In the `system-reboot` case, the function checks if the node is already cordoned (meaning an out-of-band process cordoned the node), in which case the …
> [1] - Label action handling for uncordoning after reboot

- scripts/build-binaries
- scripts/upload-binaries-to-github
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/run-test
- test/license-test/run-license-test.sh
N/A
- Fix up some supporting build scripts wrt to make args (specifying -f Makefile and -s) 
- deleted some unnecessary code and reused make targets that were doing the same thing
- Added K8s 1.17 to help text in test files that was missed when 1.17 support was introduced
---
> fix supporting build scripts wrt make args

- cmd/node-termination-handler.go
- pkg/drainevent/drain-event.go
- pkg/drainevent/scheduled-event.go
- pkg/draineventstore/drain-event-store.go
- pkg/draineventstore/drain-event-store_test.go
- pkg/ec2metadata/ec2metadata.go
- pkg/node/node.go
- pkg/webhook/webhook.go
- test/e2e/maintenance-event-cancellation-test
- test/e2e/maintenance-event-dry-run-test
- test/e2e/spot-interruption-dry-run-test
- test/ec2-metadata-test-proxy/cmd/ec2-metadata-test-proxy.go
- test/k8s-local-cluster-test/run-test
This PR will handle persisted drain events after a node is rebooted for scheduled maintenance. If a node is cordoned and drained for a qualifying reboot scheduled maintenance event, the event-id, timestamp, and an action label is added to the node. After the instance reboots, a handler will query for these labels, determine if the node has been rebooted by looking at uptime, tell the drain event store to ignore the event id (since there is latency between a scheduled maintenance event being completed and the status being flipped to complete within IMDS), uncordon the node, and then remove the NTH labels on the node. 
---
By submitting this pull request, I confirm that my …
> ignore completed drain events after reboot

- pkg/node/node.go
Handle dry-run events when labeling and removing labels from a node
---
> respect dry-run on node labels

- pkg/draineventstore/drain-event-store_test.go
- pkg/webhook/webhook_test.go
```
?   	github.com/aws/aws-node-termination-handler/cmd	[no test files]
ok  	github.com/aws/aws-node-termination-handler/pkg/config	0.040s	coverage: 98.6% of statements
ok  	github.com/aws/aws-node-termination-handler/pkg/drainevent	0.272s	coverage: 1.4% of statements
ok  	github.com/aws/aws-node-termination-handler/pkg/draineventstore	0.256s	coverage: 100.0% of statements
ok  	github.com/aws/aws-node-termination-handler/pkg/ec2metadata	1.346s	coverage: 100.0% of statements
?   	github.com/aws/aws-node-termination-handler/pkg/node	[no test files]
?   	github.com/aws/aws-node-termination-handler/pkg/test	[no test files]
ok  	github.com/aws/aws-node-termination-handler/pkg/webhook	6.263s	coverage: 100.0% of statements
?   	github.com/aws/aws-node-termination-handler/test/ec2-metadata-test-p …
```
> Bringing webhook and draineventstore to 100% coverage

- cmd/node-termination-handler.go
- pkg/config/config.go
- pkg/config/config_internal_test.go
- pkg/config/config_test.go
Rewrote config.go to return errors instead of panicking in place. As a result, flags and their default values are all declared in an object of type map[string]map[string]interface{}. Each flag is then evaluated for validity and the resulting values are stored in a map[string]interface{} which is eventually json marshaled into the nthConfig. The new changes were necessary to help consolidate error checking and avoid repeatedly checking if error else do something. 
Changes fully unit tested: 
```
ok  	github.com/aws/aws-node-termination-handler/pkg/config	0.027s	coverage: 98.6% of statements
```
> Update config to return err & add unit tests

- pkg/drainevent/spot-itn-event.go
- pkg/drainevent/spot-itn-event_test.go
spot-itn-event.go is 100% covered. 33.3% of draineventstore covered
```
=== RUN   TestTimeUntilEvent
--- PASS: TestTimeUntilEvent (0.00s)
=== RUN   TestMonitorForSpotITNEventsSuccess
2020/01/31 11:13:32 Sending drain event to the drain channel
--- PASS: TestMonitorForSpotITNEventsSuccess (0.01s)
=== RUN   TestMonitorForSpotITNEventsMetadataParseFailure
2020/01/31 11:13:32 Request failed. Attempts remaining: 2
2020/01/31 11:13:32 Sleep for 2.973889705s seconds
{12345678-1234-1234-1234-123456789012 SPOT_ITN Spot ITN received. 12345 will be INSTANCE_ACTION at 2017-09-18T08:22:00Z
2017-09-18 08:22:00 +0000 UTC 0001-01-01 00:00:00 +0000 UTC false <nil>}
2020/01/31 11:13:35 Request failed. Attempts remaining: 1
2020/01/31 11:13:35 Sleep for 8.84038228s seconds
--- PASS: …
```
> Add unit tests for spot-itn-event

- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/ec2-metadata-test-proxy/templates/daemonset.yaml
- test/e2e/maintenance-event-cancellation-test
- test/e2e/maintenance-event-dry-run-test
- test/e2e/maintenance-event-reboot-test
- test/e2e/maintenance-event-test
- test/e2e/spot-interruption-dry-run-test
- test/e2e/spot-interruption-test
- test/e2e/webhook-test
https://github.com/aws/aws-node-termination-handler/issues/74
if following the EKS documentation [here](https://docs.aws.amazon.com/eks/latest/userguide/restrict-ec2-credential-access.html) customers would not be able to use this handler as it prevents forwarding metadata, changing the pod spec to hostnetwork allows the daemonset pod to continue to get information from metadata service
> adding hostnetwork to daemonset pod spec

- config/helm/aws-node-termination-handler/templates/psp.yaml
#74 
#85 
With the latest changes to `hostNetwork`, podSecurityPolicy needs to allow that setting "`hostNetwork = true`"
> Updating psp to support latest hostNetwork setting

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/templates/psp.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
podSecurityContext was in readme and values, but not in any chart, so i removed it
securityContext - privileged was set to true when it didnt need to be
values image.tag 1.1.0 -> 1.2.0
> removing security context from chart and updating tag version

- cmd/node-termination-handler.go
- config/helm/ec2-metadata-test-proxy/templates/daemonset.yaml
- config/helm/ec2-metadata-test-proxy/values.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/drainevent/scheduled-event.go
- pkg/drainevent/scheduled-event_test.go
- pkg/drainevent/spot-itn-event.go
- pkg/drainevent/spot-itn-event_test.go
- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_internal_test.go
- pkg/ec2metadata/ec2metadata_test.go
- test/e2e/imds-v2-test
- test/e2e/maintenance-event-cancellation-test
- test/e2e/maintenance-event-dry-run-test
- test/e2e/maintenance-event-reboot-test
- test/e2e/maintenance-event-test
- test/e2e/spot-interruption-dry-run-test
- test/e2e/spot-interruption-test
- test/ec2-metadata-test-proxy/cmd/ec2-metadata-test-proxy.go
- test/k8s-local-cluster-test/run-test
https://github.com/aws/aws-node-termination-handler/issues/22
Support IMDSv2 w/ an IMDSv1 fallback. There is no configuration since imdsv2 should always be favored, but will fallback to imdsv1 if there is an issue or if it's blocked due to a container hop if not configured with a TTL of 2. 
> imdsv2 support

- config/helm/ec2-metadata-test-proxy/templates/_helpers.tpl
- config/helm/ec2-metadata-test-proxy/templates/clusterrole.yaml
- config/helm/ec2-metadata-test-proxy/templates/clusterrolebinding.yaml
- config/helm/ec2-metadata-test-proxy/templates/daemonset.yaml
- config/helm/ec2-metadata-test-proxy/templates/psp.yaml
- config/helm/ec2-metadata-test-proxy/templates/regular-pod-test.yaml
- config/helm/ec2-metadata-test-proxy/templates/serviceaccount.yaml
- config/helm/ec2-metadata-test-proxy/values.yaml
- test/k8s-local-cluster-test/kind-two-node-cluster.yaml
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/psp-default.yaml
- test/k8s-local-cluster-test/psp-privileged.yaml
This change enables the PodSecurityPolicy Admission Controller to make the integration tests look more like a production environment. This is especially important since NTH ships with a PSP that previously had not been exercised during integration testing. 
> enable PodSecurityPolicy admission controller on e2e test clusters

- scripts/generate-k8s-yaml
https://github.com/aws/aws-node-termination-handler/issues/100
After running 'helm template' there were still helm specific annotations in the yaml files.  This change simply removes any lines that start with helm.sh or app.kubernetes.io/managed-by: Helm in the aggregate and individual files before they are packaged up.
> removing helm specific annotations from generated yaml files

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/values.yaml
n/a
Add a (by default empty) image pullSecrets field to the pod so a private docker registry that needs authentication can be used.
> Add image.pullSecrets variable for private docker registries

- cmd/node-termination-handler.go
- pkg/config/config.go
- pkg/drainevent/spot-itn-event.go
- pkg/drainevent/spot-itn-event_test.go
- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_test.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
- test/e2e/webhook-test
- test/ec2-metadata-test-proxy/cmd/ec2-metadata-test-proxy.go
Issue #104 #94 , if available:
https://github.com/aws/aws-node-termination-handler/issues/104
https://github.com/aws/aws-node-termination-handler/issues/94
Updating the metadata associated with a drain event. The information returned from the event itself is now correctly populating the InstanceAction object. Additional relevant node metadata is retrieved from the instance metadata service. 
> Update DrainEvent metadata

- pkg/config/config_test.go
- pkg/drainevent/scheduled-event_internal_test.go
- pkg/drainevent/scheduled-event_test.go
- pkg/drainevent/spot-itn-event_test.go
- pkg/draineventstore/drain-event-store_test.go
- pkg/node/node_internal_test.go
- pkg/node/node_test.go
- pkg/webhook/webhook_test.go
Assert unit test args were not in the correct order. Fixed now. 
> Fix assert unit tests

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/values.yaml
https://github.com/aws/eks-charts/pull/81
Allows for configuration of dnsPolicy and sets the default to `ClusterFirstWithHostNet`
> helm dnsPolicy is configurable and defaults to ClusterFirstWithHostNet

- .travis.yml
- Makefile
- scripts/build-docker-images
- scripts/push-docker-images
https://github.com/aws/aws-node-termination-handler/issues/8 (not quite to windows support yet, but this is a good first step) 
- Added multi-arch build scripts w/ a manifest for docker images 
- Separated the building and pushing of docker images
- Changed build-binaries to look like the build-docker-images script 
> streamline builds scripts for binaries and docker images

- pkg/ec2metadata/ec2metadata.go
https://github.com/aws/aws-node-termination-handler/issues/121
- Configures the http client connection pool and client timeout so that connections are appropriately closed. 
> httpclient conn pool and request timeout config

- Dockerfile
- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
Locks down some access from NTH:
- Makes the root container filesystem read only
- Runs as non-root
- Disallow privilege escalation explicitly
- change uptime volume mount to readonly
> restrict filesystem and volume writes from container and run as non-root

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/values.yaml
- test/e2e/maintenance-event-dry-run-test
- test/e2e/maintenance-event-reboot-test
- test/e2e/spot-interruption-dry-run-test
- test/e2e/webhook-test
- test/k8s-local-cluster-test/run-test
https://github.com/aws/aws-node-termination-handler/issues/127
- Default the helm chart to tolerate all taints so that NTH runs on all nodes.
- Fix integ tests to check worker pod since NTH is now running on worker and control-plane node
> helm template default to tolerate all taints

- pkg/drainevent/scheduled-event.go
- pkg/drainevent/scheduled-event_test.go
- pkg/draineventstore/drain-event-store.go
- test/e2e/maintenance-event-cancellation-test
- test/go-report-card-test/run-report-card-test.sh
N/A
- Was spelling canceled with two L's :(   Changed all occurrences and added a test to enforce the 1 L canceled variant. 
> fix spelling of canceled for scheduled maintenance events

- .travis.yml
- test/k8s-local-cluster-test/provision-cluster
NA
- Add k8s 1.18 to travis test matrix and support in integ tests
- Update kind patched node image hashes (and add k8s 1.18)
- Update helm minor version (3.0.2 -> 3.1.2)
> support k8s 1.18 testing

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/templates/clusterrole.yaml
- config/helm/ec2-metadata-test-proxy/templates/clusterrole.yaml
Issue #138, if available:
Deleted the the line in the cluster role config file that gives NTH permission to delete daemonsets. 
> Remove unnecessary delete daemonset permission

- pkg/interruptionevent/scheduled-event.go
- test/ec2-metadata-test-proxy/cmd/ec2-metadata-test-proxy.go
https://github.com/aws/aws-node-termination-handler/issues/147
Fix bug where scheduled maintenance events times were parsed wrong. This would cause scheduled event handling to fail when the date of the start or end time was a 1 digit day.  We were assuming the day digit would always be padded with a 0 to make it two digits. 
Updated the test and date parsing string.  
> fix time parsing for scheduled maintenance events

- THIRD_PARTY_LICENSES
This should've been included in the json logging change I made, but I missed it because it's an indirect dependency. 
> Add goji license that was missed from json logging change

- cmd/node-termination-handler.go
- pkg/config/config.go
- pkg/ec2metadata/ec2metadata.go
- pkg/interruptionevent/scheduled-event.go
- pkg/interruptionevent/spot-itn-event.go
- pkg/node/node.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
Issue #, if available: none
This reverts the date format in the logs back to how it was before PR https://github.com/aws/aws-node-termination-handler/pull/152. This doesn't affect the ability to use JSON logging, it only changes the human-readable format. 
The thinking is that it was wrong to modify the format in a minor release, so we'll revisit changing the log format when we're close to version 2.0.0.
> Revert date format in human-readable logs

- pkg/webhook/webhook.go
- test/assets/squid.conf
- test/e2e/webhook-http-proxy-test
N/A
The newly added webhook-http-proxy-test was failing when testing with an actual https endpoint because the squid access log was not being written until the connection was closed. However, the go http client was keeping the connection open in the connection pool for reuse. There's no reason to reuse the http connection since the webhook is a one-time request and most often the instance is about to be terminated. 
- Set IdleConnTimeout to 1 second on the webhook http client
- Switch Squid from daemon logging to stdio logging for instant flush
- Use the full docker image hash for squid 
> set idle conns timeout on webhook http client

- scripts/push-docker-images
N/A
Turning on experimental docker cli would not work if the docker config did not already exist.
- Generate minimal docker config if one does not exist
- Remove perl to switch on experimental and instead use jq
> fix enabling docker cli experimental features in travis env

- test/e2e/prometheus-metrics-test
- test/e2e/webhook-http-proxy-test
- test/k8s-local-cluster-test/run-test
N/A
From local tests, this stabilizes the end-to-end tests....
Issues found:
1. There was a timing issue when selecting the worker pod if a pod from another test had recently been terminated and was still displayed with kubectl get pods. This is fixed by sorting by creationTime (taking the newest launched) and only look for running pods.
1. The webhook-http-proxy test checks the squid access logs to make sure it received the webhook, but the logged entry was a TCP_MISSED_ABORT/200 which was not being accepted as a success, but it should have been. 
> stabilize e2e tests

- .travis.yml
- Makefile
- test/e2e/maintenance-event-cancellation-test
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
N/A
Some travis build improvements:
1. Build Binaries on every PR / push to make sure those processes always work
1. Build Docker Images on every PR / push to make sure those processes always work
1. Generate K8s yaml resource files from the helm template to make sure those processes always work
1. Name the travis jobs
> travis build improvements

- README.md
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.yaml
- test/e2e/webhook-secret-test
Issue #170
Description of changes: `WEBHOOK_URL` is treated as a secret/private by some organizations since it gives the ability to send a message to a group of people e.g. in a slack channel. Allow users to specify Webhook URL as a secret.
> Add support for Webhook URL as a Secret

- cmd/node-termination-handler.go
- test/e2e/prometheus-metrics-test
There was a typo in the Prometheus metric's label.
> Fixed typo in "pre-dain" NodeAction

- README.md
Issue #, if available: #187
This adds documentation on which EC2 metadata endpoints the termination handler relies on.
It also provides a config option to enable the termination handler to function properly on a cluster that has Kiam deployed to manage AWS IAM credentials.
> Add metadata endpoint and Kiam documentation

- pkg/interruptionevent/scheduled-event.go
- pkg/interruptionevent/scheduled-event_test.go
Overview:
When processing scheduled maintenance events, do not fail when scheduled event does not have an end date. This information is not present for all events and is not utilized in the functionality of aws-node-termination-handler. It only serves as additional, nice-to-have information for logging/webhook msg purposes. 
https://github.com/aws/aws-node-termination-handler/issues/147
- Made end-time parsing optional for scheduled event processing. Still logging that the parsing failed, but it will now continue to send the event over the channel for potential cordon+drain.
> do not fail when scheduled event does not have end date

- .travis.yml
- Makefile
- config/helm/aws-node-termination-handler/templates/_helpers.tpl
- config/helm/ec2-metadata-test-proxy/templates/daemonset.yaml
- config/helm/ec2-metadata-test-proxy/templates/regular-pod-test.yaml
- scripts/generate-k8s-yaml
- test/helm/helm-lint
N/A
- Change helm helper kube-version retrieval to use Major/Minor instead of Version since it's supported in helm v2 and v3
- Add helm v2 and v3 linting to travis
> Kube version helm

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
Issue aws/eks-charts#198, if available:
* Add affinity to aws-node-termination-handler to not schedule on a
fargate node
Per https://github.com/aws/eks-charts/pull/199#issuecomment-655545982 I'm creating a PR on this repo instead.
> Don't schedule aws-node-termination-handler on fargate nodes

- pkg/config/config.go
The `ignore-daemon-sets` flag is [compatible with `kubectl drain --ignore-daemonsets`](--ignore-daemonsets). It literally ignores daemon sets to proceed a drain. However, the description of `ignore-daemon-sets` flag says
>If true, drain daemon sets when a spot interrupt is received.
This is the opposite meaning of what exactly this flag wants to do.
> Fix explanation of ignore-daemon-sets flag

- config/helm/aws-node-termination-handler/templates/_helpers.tpl
- config/helm/ec2-metadata-test-proxy/templates/daemonset.yaml
- config/helm/ec2-metadata-test-proxy/templates/regular-pod-test.yaml
https://github.com/aws/aws-node-termination-handler/issues/193
- Fix semver comparison in the helm chart when the server provider's major number includes a "+" like in the case of EKS. 
> remove + from major minor server version

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
Issue #202
**Description**
Correctly convert value into YAML.
Verified that generating chart template with `--set nodeSelector.lifecycle=spot,nodeSelector.foo=bar` outputs:
```yaml
nodeSelector:
kubernetes.io/os: linux
foo: bar
lifecycle: spot
```
> fix helm chart nodeSelector (#202)

- README.md
- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_test.go
- test/e2e/webhook-test
Issue #, if available: 183
Added AvailabilityZone field to NodeMetadata struct to be used in the webTemplate. Added tests and updated docs per this change.
> Update ec2metadata package to include AvailabilityZone info

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/podmonitor.yaml
- config/helm/aws-node-termination-handler/values.yaml
Since Prometheus metrics are now available, we want to be able to scrape those metrics. This PR adds a container port for the prometheus metrics and creates a `PodMonitor` to scrape the `/metrics` endpoint. Fixes issue: https://github.com/aws/aws-node-termination-handler/issues/204
By adding the following values
```
podMonitor:
create: true
interval: 30s
sampleLimit: 5000
labels:
prometheus: kube-prometheus
```
Generates the following PodMonitor
```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
name: release-name-aws-node-termination-handler
namespace: default
labels:
app.kubernetes.io/name: aws-node-termination-handler
helm.sh/chart: aws-node-termination-handler-0.9.1
app.kubernetes.io/instance: release-name
k8s-app: aws-node-termination-handler …
```
> Add PodMonitor for Prometheus Metrics

- test/e2e/webhook-secret-test
N/A
- Cleanup Webhook Secret after the test runs so that another test can be run on the same cluster
> cleanup webhook secret after each test run

- test/e2e/webhook-http-proxy-test
N/A
- webhook-http-proxy-test
- print squid logs on failure 
- improve access log grep to only look for the webhook proxy server address
> webhook-http-proxy-test: print squid logs on failure and improve access log grep

- test/e2e/webhook-http-proxy-test
https://github.com/aws/aws-node-termination-handler/pull/214
- Turns out the changes in https://github.com/aws/aws-node-termination-handler/pull/214 breaks the tests on a real webhook endpoint (or at least an endpoint with a context path).
- The squid access logs only log the domain, not the context path, so need to truncate the full URL to just the domain. 
- Also, sometimes squid takes an eternity to start up, so added a while loop to wait for it to come up
> squid fixes for webhook-http-proxy-test

- Dockerfile.windows
- config/helm/squid/templates/daemonset.yaml
- config/helm/squid/templates/service.yaml
- config/helm/webhook-test-proxy/templates/daemonset.yaml
- test/e2e/webhook-http-proxy-test
- test/e2e/webhook-secret-test
- test/e2e/webhook-test
- test/k8s-local-cluster-test/run-test
N/A
- Only deploy NTH pod to worker node in e2e tests.
- This solves an issue with coredns being evicted and causing webhook failures. 
> only deploy to worker node on e2e tests

- config/helm/webhook-test-proxy/templates/daemonset.yaml
- config/helm/webhook-test-proxy/templates/service.yaml
- config/helm/webhook-test-proxy/values.yaml
- test/e2e/webhook-http-proxy-test
- test/e2e/webhook-secret-test
- test/e2e/webhook-test
- test/eks-cluster-test/run-test
- test/k8s-local-cluster-test/run-test
N/A
- Webhook test proxy now runs as a k8s service w/ a static port number (80)
- Added the security context config for linux on the webhook daemonset 
> fix webhook tests

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/values.yaml
According to the README, the default value for enableSpotInterruptionDraining is true, but the value in values.yaml had it set to empty string (""). 
> default enableSpotInterruptionDraining to true

- scripts/push-docker-images
Issue #, if available: 
* N/A
* `MANIFEST_IMAGES` is an array; existing images in the manifest will be added directly here
* using `manifest create --amend` because for-loop is the only way I can get Windows to register multiple manifest images at once
* fixed spacing
* added more `echo` for easier debugging in Travis
> fix manifest updating in push-docker-images

- README.md
N/A
- Add Amazon EC2 Spot Instances Integration Roadmap to readme
> Add Amazon EC2 Spot Instances Integration Roadmap to readme

- Dockerfile
- Dockerfile.windows
- Makefile
- README.md
- go.mod
- go.sum
- test/webhook-test-proxy/Dockerfile
- test/webhook-test-proxy/Dockerfile.windows
N/A
- Upgrade to go 1.15
- Use GOPROXY piping to fallback to direct if golang proxy return an error
- Ran go mod tidy
- Stripped debug tables from binaries. 
> upgrade to go 1.15

- config/helm/aws-node-termination-handler/templates/podmonitor.yaml
I am trying to use the new PodMonitor but I am getting a parsing error when deploying.
I am using the following version of helm:
```bash
Client: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.3", GitCommit:"1ee0254c86d4ed6887327dabed7aa7da29d7eb0d", GitTreeState:"clean"}
```
This is the command I ran to get the error:
```bash
$ helm template aws-node-termination-handler eks/aws-node-termination-handler --version 0.9.4 --namespace=kube-system --set enablePrometheusServer=true --set podMonitor.create=true
UPGRADE FAILED
Error: YAML parse error on aws-node-termination-handler/templates/podmonitor.yaml: error converting YAML to JSON: yaml: line 12: did not find expected key
Error: UPGRADE …
```
> fix identation on PodMonitor

- test/license-test/run-license-test.sh
N/A
- Only generate linux/amd64 binary for license analysis to speed up travis
> only build one binary to check licenses

- scripts/push-docker-images
- scripts/upload-resources-to-github
- test/e2e/cordon-only-test
- test/e2e/imds-v2-test
- test/e2e/maintenance-event-cancellation-test
- test/e2e/maintenance-event-dry-run-test
- test/e2e/maintenance-event-reboot-test
- test/e2e/maintenance-event-test
- test/e2e/prometheus-metrics-test
- test/e2e/spot-interruption-dry-run-test
- test/e2e/spot-interruption-test
- test/e2e/webhook-http-proxy-test
- test/e2e/webhook-secret-test
- test/e2e/webhook-test
- test/eks-cluster-test/reset-cluster
- test/eks-cluster-test/run-test
- test/go-report-card-test/run-report-card-test.sh
- test/helm-sync-test/run-helm-sync-test
- test/helm-sync-test/run-helm-version-sync-test
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/delete-cluster
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
- test/license-test/gen-license-report.sh
- test/shellcheck/run-shellcheck
N/A
There have been a lot of build/test/deployment script changes lately and have caused some problems since these scripts are difficult to test locally. As an enhanced safety measure, which would've caught some of these errors, this PR clears up shellcheck warnings and now only passes if shell scripts do not contain warnings. Before, shellcheck was only set to fail on errors. 
> clear up shellcheck warnings

- test/helm-sync-test/run-helm-sync-test
N/A
- Helm Sync Test array appending was incorrectly adding the whole array as one element for clone_urls and branches
> fix helm test

- cmd/node-termination-handler.go
- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_test.go
#229 
Added a for loop for getting scheduled maintenance events and spot instance events. Set the retry limit to 1. 
Not sure of the best way to add this to the test suite. Also curious if throwing a panic to sovle the second item in the issue is what's best to do here or not. 
> Add retries when reponse from IMDSv2 retruns a 401

- test/e2e/maintenance-event-cancellation-test
N/A
- Missed a retry on the second install of AEMM in the maintenance-event-cancellation e2e test. 
> retry second AEMM install in maintenance-event-cancellation-test

- cmd/node-termination-handler.go
- pkg/interruptioneventstore/interruption-event-store.go
- pkg/interruptioneventstore/interruption-event-store_test.go
- pkg/monitor/scheduledevent/scheduled-event-monitor.go
- pkg/monitor/spotitn/spot-itn-monitor.go
- pkg/node/node.go
#250 
Reduce the congestion of event logging by only logging for new events. No behavioral changes.
---
**Upside:** Better looking logs
Human readable example
```
2020/09/09 16:06:44 Kubernetes AWS Node Termination Handler has started successfully!
2020/09/09 16:06:44 Started monitoring for SPOT_ITN events
2020/09/09 16:06:44 Started watching for event cancellations
2020/09/09 16:06:46 Adding new event to the event store event={"Description":"Spot ITN received. Instance will be interrupted at 2020-09-09T16:10:47Z \n","Drained":false,"EndTime":"0001-01-01T00:00:00Z","EventID":"spot-itn-a47ba0ecd3e0bf3a0023591eaf85caf67eb18a13a7c4a5e3d0c2a9885d19c791","Kind":"SPOT_ITN","NodeName":"ip-123-456-789-123.us-east-2.compute.internal","StartTime":"2020- …
```
> Reduce event logging to only new events

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/webhook/webhook.go
When the destination of the webhook requires a more complex message content, it can be easier to provide a json template file which will be mounted into the pod, rather than having the webhook message content set in an inline variable.
This will allow users to set a WEBHOOK_TEMPLATE_FILE environment variable (--webhook-template-file argument) to set the template file path which will be used to send the webhook message. This takes precedence over the --webhook-template argument.
Template file will have to exist (be mounted into the pod as volume by users) otherwise it will throw an error.
Example: 
```
---
apiVersion: v1
data:
webhook-alert-template.json: |-
{
"status": "firing",
"alerts": [
{
"status": "firing",
"labels": {
"alertname": "myalert",
"region": …
```
> Allow users to configure webhook message content with a template file

- docs/aemm_interruption_testing.md
#208 
Moves the information about using AEMM to simulate a spot interruption from this issue into a more permanent location
> Add AEMM mock interruption documentation

- cmd/node-termination-handler.go
- pkg/config/config.go
- pkg/ec2metadata/ec2metadata.go
- pkg/monitor/scheduledevent/scheduled-event-monitor.go
- pkg/monitor/scheduledevent/scheduled-event-monitor_internal_test.go
- pkg/monitor/spotitn/spot-itn-monitor_internal_test.go
- pkg/node/node.go
- pkg/node/node_internal_test.go
- pkg/node/node_test.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
#249 
Reformat logs so that they actually use json formatting for the errors and fields instead of hiding those values within the 'message' field.
**Question** - should we make the log key format more consistent? 
- Standard keys like 'message', 'time', and 'error' are lowercase due to zerolog defaults
- The arguments are logged in kebab case to match the old format. 
- Custom keys like 'NodeName' are pascal case because I matched them against how .Interface() values are logged (they match their struct names which are pascal case) 
I'm learning toward making all the keys we control snake_case.
> Reformat logs to support proper JSON logging

- .gitignore
- cmd/node-termination-handler.go
- go.sum
Description of changes: 
Recently, we had an edge case scenario where NTH daemon failed to uncordon the node with below error message:
```
"Unable to complete the uncordon after reboot workflow on startup: Unable to fetch kubernetes node from API: Get " https://172.20.0.1:443/api/v1/nodes/ip-10-79-29-243.us-east-2.compute.internal": dial tcp 172.20.0.1:443: i/o timeout errors. 
```
Debugging further, we could neither find any issue with kube-proxy d/s or aws-node d/s which constantly talks to API server upon which we thought this could be a transient network issue due to which NTH failed to uncordon the node. 
That said, from a distributed systems stand point, we should be able to handle any such network partition events for at least short period of time without …
> Retry uncordon workflow to handle transient network issues

- cmd/node-termination-handler.go
- pkg/node/node.go
- pkg/node/node_test.go
N.A.
To log all pods that are potentially affected by a spot interruption.
1. Logging the pod names can be another `PreDrainTask`, but that would require the PreDrainTask of `monitor.InterruptionEvent` to be changed to a slice and much more code changes. On the other hand, for a scheduled maintenance, there is no need to log all pod names.
1. Make `LogPods ` and `fetchAllPods` a member function of Node such that they can potentially be reused.
1. Change a bit in the test cases to see if the logging works properly.
✅  By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
> Log all pods on a node when cordoning the node

- pkg/monitor/sqsevent/sqs-monitor.go
This change adds debug log messages to give hints when an Auto Scaling
Group is not tagged as managed. Without this change there's no other
indication that the instance & ASG is unmanaged and makes diagnosing
this condition quite difficult without reading through the source code.
> Add debug log messages to `isInstanceManaged`

- .travis.yml
- Makefile
- scripts/create-local-tag-for-release
- scripts/prepare-for-release
- scripts/sync-to-aws-eks-charts
- test/helm-sync-test/run-helm-sync-test
* N/A , automating release process across repos
* adds `make` targets to create tag, update versions, and submit PR for release
* adds `make` targets for submitting PR to *aws-eks-charts* if diff is detected
* will always be kicked off during NTH releases
Testing:
* this might finish eventually: https://travis-ci.org/github/brycahta/aws-node-termination-handler/builds/742788027
> Autom8 release

- .travis.yml
- Makefile
- scripts/prepare-for-release
* update ReadMe versions post-release so we don't create the opportunity for users to try and pull a release version that is currently in progress
- add travis target to submit PR to update ReadMe versions
- corrected automated commit msg when updating ReadMes only (intended for post-release only)
Testing:
- tested `make create-release-prep-pr-readme` and `make create-release-prep-pr` locally and saw expected file changes and PR/Commit messaging 
> update readme versions post-release

- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_internal_test.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
Removes the `NTHManagedASG` tag constant in favor of a configurable `ManagedAsgTag` option to allow you to run NTH in queue mode across multiple clusters in an account. EC2 instance events don't have any filtering ability currently, which will cause NTH to drop into a crash loop when it runs into an error while trying to cordon a node that doesn't exist in the cluster. See [here](https://github.com/aws/aws-node-termination-handler/blob/5150b31c819a26c2cc80f812ffb0a0b317290b56/cmd/node-termination-handler.go#L260-L280).
Fixes #272
> Allow the NTHManagedAsg tag to be configurable

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
When trying to use aws-node-termination-handler with `webhookTemplateConfigMapName` and `webhookTemplateConfigMapKey` configured, following error occurs:
```text
Error: UPGRADE FAILED: cannot patch "aws-node-termination-handler" with kind DaemonSet: DaemonSet.apps "aws-node-termination-handler" is invalid: [spec.template.spec.volumes[1].name: Invalid value: "webhookTemplate": a DNS-1123 label must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'), spec.template.spec.containers[0].volumeMounts[1].name: Not found: "webhookTemplate"]
```
This PR fixes those names.
see also: https://github.com/aws/eks-charts/pull/363
By …
> Fix volume name of daemonsets to follow DNS-1123 label standard

- .travis.yml
- Makefile
- scripts/sync-to-aws-eks-charts
- test/helm/validate-chart-versions
* copy to eks-charts command had a typo
* no automated checks to prompt user to increment chart version
* no automated checks following EC2-Bot's PR to eks-charts
* fixed typo
* added `validate-chart-versions` which will check NTH's latest commit Helm Chart Version (what is currently running in Travis) against the latest released version in eks-charts
* if the commit edited Helm files, but chart versions are the same then FAIL because chart version in NTH should be incremented
* if the commit edited Helm files, but the chart versions are different then SUCCEED
* note, there is still some manual checking from the review to ensure **correctness** of the chart version
* if the commit did not edit Helm files, then SUCCEED
* added Makefile target …
> Update automated release

- cmd/node-termination-handler.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
NTH crashes often from "EC2 Instance State-change Notification" events.
fixes https://github.com/aws/aws-node-termination-handler/issues/307
The underlying issue was that an empty parsed NodeName derived from PrivateDnsName for forwarded unverified, creating cascading problems.
This solves the root cause, that "EC2 Instance State-change Notification" can arrive at a time where the instance is in shutting-down, terminated or any other not-online situation where the PrivateDnsName metadata is empty!
Instead of just ignoring these errors this implementation gets and decides based on the state of the instance message if it is an error to fail or to ignore.
Therefor such messages are dropped in above situation because they are useless.
@haugenj 
Background: went all the way back, instead of …
> 🐛 fixing crashes on State-change events

- cmd/node-termination-handler.go
no issue
We're comparing the error objects instead of their contained errors. `err` is new on each loop so it'll never be equal to `previousErr`
Proof is in the playground: https://play.golang.org/p/o5ezN5xvaSy
> Fix duplicate error equality check

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
* N/A: helm param for log level was missing
* added param
Testing:
* added various log levels (debug, info, error) to e2e tests, executed locally, and saw pod logs reflected the configuration
> add log-level helm param

- Makefile
- config/helm/aws-node-termination-handler/values.yaml
- scripts/ecr-public-login
- scripts/retag-docker-images
https://github.com/aws/eks-charts/issues/356
https://github.com/aws/aws-node-termination-handler/issues/295
- Publish docker images to ECR in addition to Dockerhub
- Change helm to use ECR Public by default
> publish images to ecr public repo

- Makefile
- scripts/draft-release-notes
N/A
Add a script to draft release notes by pulling all the commits since the last release.
The releaser still needs to copy/paste the release notes into the github UI to make a release, but we can automate that part away soon.
> add script to draft release notes

- scripts/ecr-public-login
- scripts/install-awscli
- scripts/retag-docker-images
- test/shellcheck/run-shellcheck
N/A
v1.11.2's release has been stuck because of issues with the ECR login for Windows and an old version of the aws-cli installed on github actions runners.  
This PR adds:
- scripts/install-awscli which installs the specified AWS CLI version on mac, windows, or linux
- Fixes ecr-login script to work across linux, windows, and mac
- Fixes retag script to work on windows
- Fix shellcheck test to exclude the build dir
> Fix ECR login and add install-awscli script

- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/interruptioneventstore/interruption-event-store.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/types.go
Issue #310
This replaces the single process execution of events to parallel processing, solving the issue that happens when NTH is busy / blocked (retrying to evict) and eventually will miss to process events for other nodes going down the same time time. 
Example: 
3 nodes roll at a time because of batchSize or spot interruption. 
A deployment has a pdb limit of maxUnavailable of 1 - that will block NTH in a eviction retry loop and it will miss the third node eviction. 
The amount of workers are capped to prevent a memory runnaway.
> multithreaded event processor

- scripts/prepare-for-release
* Last release failed because script prematurely exited when grep failed
* https://github.com/aws/aws-node-termination-handler/runs/1602759774?check_suite_focus=true
* Do not exit when grep is unable to find the previous version in documents, instead script should keep going and eventually have a file list of 0 requiring updates (and therefore no action)
* all other errors (exit code > 1) from grep will lead to script terminating
> fix update version check

- scripts/draft-release-notes
- scripts/prepare-for-release
- test/eks-cluster-test/run-test
- test/k8s-local-cluster-test/run-test
* Last release failed in 2 areas:
* the chart version was not incremented in the eks-charts PR
* gh actions errored out when trying to publish version updates to ReadMe (post release)
* one reason being previousVersion == latestVersion
* Updated `make release-prep-X` to increment Chart.yaml version as part of the Release-Prep PR
* If previousVersion == latestVersion, then fetch previous-previous version
* Add git config for ec2-bot
* Update `sed` replacement to work with Mac and Linux
* Circumvent pr-publish-prompt when updating ReadMe only (triggered by bot and considered post-release)
* Exit gracefully when no file changes required
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> fix release prep for gh actions

- .github/workflows/ci.yml
- Makefile
- README.md
- scripts/sync-readme-to-ecr-public
N/A
* add `make sync-readme-to-ecr-public` to github actions
> add sync readme to ecr public

- config/helm/aws-node-termination-handler/README.md
Issue #, if available: Fixes #349
Description of changes: Fix incorrect default in documentation for `deleteLocalData`
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. ✅
> Document that deleteLocalData defaults to true, not false

- config/helm/aws-node-termination-handler/README.md
Issue #, if available: Fixes #348
Description of changes: Clarify that grace period defaults to -1, not 30. But Kubernetes defaults to 30.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license. ✅ 
@bwagner5 Let me know if you want to tweak the language.
> Clarify podTerminationGracePeriod docs

- pkg/monitor/scheduledevent/scheduled-event-monitor.go
See Issue #361 and related #315
Hide the continual error from attempting to parse an empty string (when there isn't a `NotAfter` in the scheduled event, as in the example from #361 ).
Note this only fixes the minor point of the issue - that the node isn't immediately drained & eventually terminated remains.
> Avoid noisy error on scheduled events without NotAfter

- README.md
Issue #, if available: #346
* Moving Helm install instructions above kubectl since it is the most popular installation method and clearest in terms of configuring NTH
* Added instructions for the minimal config necessary when using kubectl. Noted that the default configs alone will not work because sqs queue will be ""
> clarify queue processor install instructions

- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/ec2-state-change-event.go
- pkg/monitor/sqsevent/rebalance-recommendation-event.go
- pkg/monitor/sqsevent/spot-itn-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
Issue #360
Fixes #360 by iterating over all messages retrieved from SQS.  The tests are also updated to process all three test events at once without spawning a go process.
I have at least one open question: 
*Should further processing of messages from the queue continue if an error is encountered?*
Currently those events are silently dropped for future retry.  SQS will bury the unprocessed events until the visibility timeout expires and then redeliver them.  A few possible options:
* Just let them get ignored.  This slows down handling of events, and is likely sub-optimal
* Continue processing the next message in the queue, but that changes the assumed semantics of Monitor() a bit, as errors couldn't be surfaced unless they're merged together.
* Forget processing multiple messages per …
> Sqs deletion issue 360

- pkg/monitor/sqsevent/sqs-monitor_test.go
- test/go-report-card-test/Dockerfile
golang version 1.16 was released this week, and they changed the default behavior of `GO111MODULE`. So now if we want it to act like it used to, we have to set `GO111MODULE=auto`. More info on `GO111MODULE` [here](https://golang.org/ref/mod#mod-commands)
It was not downloading the source files for goreportcard, so when trying to `cd` into that directory the directory did not exist.
I also ran `make fmt`, which changed one line in `sqs-monitor_test.go` 
> Fix goreportcard test and run make fmt

- config/helm/aws-node-termination-handler/templates/psp.yaml
- config/helm/aws-node-termination-handler/test.yaml
- config/helm/aws-node-termination-handler/values.yaml
When metric/prometheus endpoint is enabled, we currently have an issue as the
PodSecurityPolicy does not allow the pod to bind the ports. This change sorts
this issue out (#365).
cc @haugenj
> helm: added necessary hostPorts in the PodSecurityPolicy

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/podmonitor.yaml
- config/helm/aws-node-termination-handler/values.yaml
The pod monitor is only created in the Helm release namespace. The Prometheus operator by default watches pod monitors resources only in its own namespace. To watch resources in another namespace, it can be configured to use label selectors. However, in some cases, we do not want to add labels to an already existing namespace like kube-system.
This PR allows overriding the release namespace for the pod monitor. Some other Helm charts already support this feature like the pushgateway.
Forked the Helm chart and deployed it. Working as intended.
helm template output is working as well: previous release namespace and overridden namespace when the added namespace is uncommented.
> helm: Add support to override pod monitor namespace

- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
Issue #367, if available:
If no instances are returned from the describe instances call then there's no work to do, so we'll return a `ErrNodeStateNotRunning` error. This gets handled in the `Monitor` function - it'll delete the message and avoid the panic. 
With this we can also remove the `if nodeName == "" {` check in asg-lifecycle-event because we never actually run that. There's always a nodename by that point or we'll have already returned an error. 
> Drop sqs messages for absent nodes

- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/ec2-state-change-event.go
- pkg/monitor/sqsevent/rebalance-recommendation-event.go
- pkg/monitor/sqsevent/spot-itn-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/types.go
Issue #, if available: https://github.com/aws/aws-node-termination-handler/issues/357
Description of changes: Provide AutoScalingGroupName for webhook notifications in Queue Processor mode only as we require creds to fetch ASG name. The user can provide override sample webhook template like following:
```
`{"text":"[NTH][Instance Interruption] EventID: {{ .EventID }} - Kind: {{ .Kind }} - Node: {{ .NodeName }} - AutoScalingGroupName: {{ .AutoScalingGroupName }} - Start Time: {{ .StartTime }}"}`
``` 
> Provide AutoScalingGroupName for webhook notifications

- cmd/node-termination-handler.go
- pkg/monitor/types.go
- pkg/node/node.go
- pkg/node/node_test.go
Issue #, if available: https://github.com/aws/aws-node-termination-handler/issues/359
Description of changes: Provide list of running pods as webhook notifications. This will be available as override to default webhook template. 
Sample Webhook Template:
```
`{"text":"[NTH][Instance Interruption] EventID: {{ .EventID }} - Kind: {{ .Kind }} - Node: {{ .NodeName }} - Pods: {{ .Pods }} - Start Time: {{ .StartTime }}"}`
```
> Add running pods (soon to be evicted) to webhook notifications

- config/helm/aws-node-termination-handler/templates/clusterrole.yaml
- config/helm/prometheus-operator/templates/prometheus-operator/clusterrole.yaml
- test/e2e/prometheus-metrics-test
Issue #, if available: https://github.com/aws/aws-node-termination-handler/issues/355
Description of changes: Add permissions for 'get' to pod resources. This was causing eviction to fail internally while seeming to a successful eviction and mask all errors.  After overriding the kubectl lib and adding logs (unfortunately, missing within the package), I found the error to be:
`"spark-pi-driver" is forbidden: User "system:serviceaccount:kube-system:aws-node-termination-handler" cannot get resource "pods" in API group "" in the namespace "default"`
> Update ClusterRole to include 'get' for pods

- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/observability/probes.go
- pkg/observability/probes_test.go
Issue # , if available: #333
Description of changes: Implemented liveness probe by HTTP request. Updated helm chart to allow enable/disable liveness probe.
> Liveness probe support

- pkg/monitor/sqsevent/sqs-monitor.go
Issue #398 
Switch SQS to use the long-polling pattern (fixed max-wait of 20 seconds).  Credit to @tskinn for spotting this & happy to close this if they already have some better way of fixing this trivial PR.
> Switch to use SQS long polling

- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/test.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- test/e2e/rebalance-recommendation-drain-test
- test/e2e/rebalance-recommendation-dry-run-test
Issue #, if available: https://github.com/aws/aws-node-termination-handler/issues/368
Currently NTH will only cordon a node when a rebalance recommendation signal is received. This PR adds the ability to also drain the node when such signal is received.
Also adding a couple of missing parameters in the Helm chart.
> feat: add ability to drain on rebalance

- cmd/node-termination-handler.go
- pkg/config/config.go
- pkg/ec2metadata/ec2metadata.go
- pkg/interruptioneventstore/interruption-event-store.go
- pkg/monitor/scheduledevent/scheduled-event-monitor.go
- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/rebalance-recommendation-event.go
- pkg/monitor/sqsevent/spot-itn-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/node/node.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
- test/e2e/prometheus-metrics-test
N/A
Fix undefined log levels: 
BEFORE:
```
2021/04/02 15:44:08 ??? Trying to get token from IMDSv2
2021/04/02 15:44:15 ??? Unable to retrieve an IMDSv2 token, continuing with IMDSv1 error="Put \"http://169.254.169.254/latest/api/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
2021/04/02 15:44:18 ??? Request failed. Attempts remaining: 2
2021/04/02 15:44:18 ??? Sleep for 2.973889705s seconds
2021/04/02 15:44:23 ??? Request failed. Attempts remaining: 1
2021/04/02 15:44:23 ??? Sleep for 8.84038228s seconds
2021/04/02 15:44:34 ??? Unable to fetch metadata from IMDS error="Unable to parse metadata response: Unable to get a response from IMDS: Get \"http://169.254.169.254/latest/dynamic/instance-identity/documen …
```
> fix undefined log levels

- pkg/config/config.go
https://github.com/aws/aws-node-termination-handler/issues/390
- Fix issue with SQS queue-url region detection
> fixed and improved region detection within queue url

- cmd/node-termination-handler.go
- docs/aemm_interruption_testing.md
- pkg/interruptioneventstore/interruption-event-store.go
- pkg/interruptioneventstore/interruption-event-store_test.go
- pkg/monitor/types.go
Fix #407 
Description of changes: 
This MR rename `InterruptionEvent.Drained` to `InterruptionEvent.NodeProcessed` for better describe what this property be used for. It also rename `interruptionEventStore.MarkAllAsDrained()` to `interruptionEventStore.MarkAllAsProcessed()` also.
> rename InterruptionEvent.Drained to InterruptionEvent.NodeProcessed

- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
Issue #367, if available:
When an instance is missing the describe-instances call [returns an error](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#EC2.DescribeInstances) instead of an empty array. 
> If you specify an instance ID that is not valid, an error is returned. If you specify an instance that you do not own, it is not included in the output.
Now we'll check the error and handle that case 
> fix error handling for missing instances

- README.md
Issue #, if available: 
* #415
* Add some `s` and details
> Clarify EventBridge Rules setup

- cmd/node-termination-handler.go
- pkg/config/config.go
The region needs to be set on the config object before creating the
session so that things like setting `AWS_STS_REGIONAL_ENDPOINTS` can
take effect.
Also, if credentials cannot be acquired, die at that point instead of
carrying on.
Fixes #420
> Correct instantiation of AWS session object

- .github/workflows/ci.yml
- Dockerfile
- Dockerfile.windows
- README.md
- go.mod
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
- test/go-report-card-test/Dockerfile
- test/go-report-card-test/run-report-card-test.sh
- test/webhook-test-proxy/Dockerfile.windows
Issue #, if available: #424
* Upgrade to go 1.16
* Fixed files failing go-report-card
> Upgrade to Go 1.16 and fix report-card

- cmd/node-termination-handler.go
- test/go-report-card-test/run-report-card-test.sh
Issue #, if available: #412
Description of changes: Don't `exit(1)` on drain errors when in queue processor mode
> don't exit(1) in queue processor mode

- .github/workflows/ci.yml
- test/go-report-card-test/Dockerfile
N/A
- ECR rate limits pulls for unauthenticated users, so pull go-report-card image from dockerhub 
- Always run license tests
> always do license check and use dockerhub for go-report-card image pulls

- pkg/ec2metadata/ec2metadata.go
If IMDSv2 is unreachable or disabled on the EC2 instances, the logs
are filled with such messages without providing any real value or action
as the application fallbacks to IMDSv1 anyway.  We can move such messages
to the debug level in order to try and keep the log messages clean for
any warnings that might be missed with this flooding.
These messages probably fail into the debug category anyway as they are
mostly helpful when debugging the application.
> [ec2metadata] Switch IMDSv2 token warning message to debug

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
N/A
- Make NTH deployment replicas configurable via helm when using queue-processor mode.
> make queue-processor mode replicas configurable

- pkg/monitor/sqsevent/sqs-monitor.go
https://github.com/aws/aws-node-termination-handler/issues/413
- Change drop message log to WARN instead of ERROR
> change drop message log to WARN instead of ERR

- THIRD_PARTY_LICENSES
N/A
- Add third party licenses for sprig from https://github.com/aws/aws-node-termination-handler/pull/445
> add licenses for sprig and transitive deps

- cmd/node-termination-handler.go
N/A
- Add pod list to drain event (before it was only being added if cordon-only was enabled or rebalance events in IMDS mode)
> add pods to webhook event and log pods on node

- README.md
N/A
- The sqs queue creation command isn't quite right in the readme. The policy needs to be on a single line. 
```
$ QUEUE_POLICY=$(cat <<EOF
{
"Version": "2012-10-17",
"Id": "MyQueuePolicy",
"Statement": [{
"Effect": "Allow",
"Principal": {
"Service": ["events.amazonaws.com", "sqs.amazonaws.com"]
},
"Action": "sqs:SendMessage",
"Resource": [
"arn:aws:sqs:${AWS_REGION}:${ACCOUNT_ID}:${SQS_QUEUE_NAME}"
]
}]
}
EOF
)
$ cat << EOF > /tmp/queue-attributes.json
{
"MessageRetentionPeriod": "300",
"Policy": "$(echo $QUEUE_POLICY | sed 's/\"/\\"/g')"
}
EOF
$ cat /tmp/queue-attributes.json
{
"MessageRetentionPeriod": "300",
"Policy": "{
\"Version\": \"2012-10-17\",
\"Id\": \"MyQueuePolicy\",
\"Statement\": [{
\"Effect\": \"Allow\",
\"Principal\": { …
```
> policy should be on one line to create queue

- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
There is no need to use the hostPort option if we are not directly
connected to the hostNetwork. Using the hostPort option makes that port
unavailable for binding to any other service on the node which is
not really desirable if the pod itself is not on the host network.
ps: This is a copy of https://github.com/aws/eks-charts/pull/527
> helm: Use hostPort only with hostNetwork

- config/helm/aws-node-termination-handler/README.md
> fix typo in helm config readme

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
https://github.com/aws/eks-charts/issues/550
Note, this PR replaces https://github.com/aws/eks-charts/pull/551.
> Fix Helm templates bug which caused duplicate ports key #551

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/_helpers.tpl
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/templates/pdb.yaml
- config/helm/aws-node-termination-handler/templates/podmonitor.yaml
- config/helm/aws-node-termination-handler/templates/psp.yaml
- config/helm/aws-node-termination-handler/templates/serviceaccount.yaml
- config/helm/aws-node-termination-handler/values.yaml
Fixes https://github.com/aws/eks-charts/issues/553
- Add PodDisruptionBudget when using `enableSqsTerminationDraining` with more than 1 replica
- Add `aws-node-termination-handler.selectorLabels` template
- Refactor selector label patterns to use `aws-node-termination-handler.selectorLabels`
- Refactor labels to use the `nindent` idiomatic pattern
> [helm] Add PDB and update label patterns

- cmd/node-termination-handler.go
- pkg/node/node.go
#423
- `cordonNode` & `cordonAndDrainNode` returns nil on successful execution and hence the `podName` and `node.LogPods` is not subsequently called in current implementation.
- Pod list should be fetched before `cordonNode` or `cordonAndDrainNode`. After successful `cordonAndDrainNode` operation the running pods will be evicted from the node and pod list be will empty in that case.
- Even if `cordonNode` or `cordonAndDrainNode` fails one still needs the list of running pods in notification message to capture which all pods will be impacted by the interruption event. Helpful in debugging issues.
> fixes #423: Populate pod list in webhook notification

- README.md
NTH's SQS processor does automatically support instance state changes for EC2 instances. If a node is Terminated, either by a user or by an AWS scheduled event, we still have a small window in which to begin the drain. 
The documentation as it stands doesn't set up the EventBridge rule to enable this. I've added it to the basic setup guide here.
> Update README for instance state changes

- .github/workflows/ci.yml
N/A
- Bypass e2e due to 1 hour limitation in release pipeline (all tests have passed many times w/ no logic changes) 
> bypass e2e tests because of 1 hour limitation in release pipeline

- .github/workflows/ci.yml
Don't run builds and tests on a release since they've been run at least twice before.
> Release Faster

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
https://github.com/aws/aws-node-termination-handler/issues/484
This change will allow for additional environment variables to be passed to the NTH pod (i.e. proxy config).
> Add extraEnv to helm chart

- Dockerfile
N/A
Reduce build times by leveraging docker caching layers. Previously, go mod downloads were not cached between os/arch variants because the build args changed which resulted in docker invalidating the go mod download layer.
> fix docker layer caching

- cmd/node-termination-handler.go
- pkg/node/node.go
- pkg/node/node_test.go
Issue #, if available: Fixes #386
`drainEvent.Description` indicates the reason for needing to cordon and/or drain a node, as well as some other details like the time the event will occur. Currently, the following reasons are possible:
* [Spot ITN](https://github.com/aws/aws-node-termination-handler/blob/main/pkg/monitor/spotitn/spot-itn-monitor.go#L94)
* [Scheduled event](https://github.com/aws/aws-node-termination-handler/blob/main/pkg/monitor/scheduledevent/scheduled-event-monitor.go#L105)
* [Rebalance recommendation](https://github.com/aws/aws-node-termination-handler/blob/main/pkg/monitor/rebalancerecommendation/rebalance-recommendation-monitor.go#L92)
* [SQS event](https://github.com/aws/aws-node-termination-handler/blob/4a6f45339b20fc22f98a59fec3292684b879861 …
> Add cordon reason in log messages for cordon operations

- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
Issue #495 
1. Removed arch affinity from nodeAffinity completely
2. Removed OS node selector from nodeAffinity. As it already exists in nodeSelector
> Fix custom nodeAffinity via values.yaml

- config/helm/aws-node-termination-handler/templates/_helpers.tpl
- config/helm/aws-node-termination-handler/templates/clusterrole.yaml
- config/helm/aws-node-termination-handler/templates/clusterrolebinding.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
Support for custom labels to add into metadata of all resources
> Support custom labels

- pkg/config/config.go
- pkg/node/node.go
Add `TAINT_EFFECT` env var and `--taint-effect` flag to configure the node taint effect
Defaults to `NoSchedule`, garbage values will log a warning and default to `NoSchedule`.
closes  #273
> Add configurable taint effect

- cmd/node-termination-handler.go
Issue #545, if available:
Don't crash when failing to drain a node due to a PDB.
> Remove exit when cordon failed

- config/helm/aws-node-termination-handler/templates/deployment.yaml
If `webhookTemplateConfigMapName` and `webhookTemplateConfigMapKey` are not set in the values.yaml file, we end up with a deployment.yaml file that has key `volumes` with a `nil` value. This causes other tools like `kustomize` to throw warnings:
```
2022/01/03 18:04:29 nil value at `volumes.configMap.name` ignored in mutation attempt
2022/01/03 18:04:29 nil value at `volumes.projected.sources.configMap.name` ignored in mutation attempt
2022/01/03 18:04:29 nil value at `volumes.secret.secretName` ignored in mutation attempt
2022/01/03 18:04:29 nil value at `volumes.projected.sources.secret.name` ignored in mutation attempt
2022/01/03 18:04:29 nil value at `volumes.persistentVolumeClaim.claimName` ignored in mutation attempt
```
This PR wraps the `volumes` key in the …
> Wrap volumes key in conditional to protect from being nil

- scripts/push-docker-images
Description of changes: We only publish container images to ECR now, so we're removing any remaining references to our previous Docker Hub workflows. This appears to be the last one.
> Remove last reference to Docker Hub and use a more precise term

- config/helm/aws-node-termination-handler/Chart.yaml
🥑🤖 Auto-generated PR for v1.14.1 release. Updating release versions in repo.
> 🥑🤖 v1.14.1 release prep

- .github/workflows/ci.yml
> use gha cache

- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
Issue #  [573](https://github.com/aws/aws-node-termination-handler/issues/573)
Description of changes: Fixed yml Indentation in deployment.yml, daemonset.linux.yml and daemonset.windows.yml files.
> Issue-573: Fixed Helm chart Indentation

- README.md
- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
Issue #, if available: #356
* Check SQS message for a Lifecycle termination event sent directly from ASG to SQS (different schema than from EventBridge to SQS)
* Update README with new/updated instructions to set up Lifecycle hook and IAM access roles
These changes are meant to help support only Lifecycle termination events from ASG sent to SQS.
> Support ASG-to-SQS Lifecycle Termination events

- .github/workflows/build-and-test.yaml
* https://github.com/aws/aws-node-termination-handler/issues/589
* https://github.com/golangci/golangci-lint-action/issues/23
Moving `golangci-lint` into its own job per the [updated onboarding instructions](https://github.com/golangci/golangci-lint-action#how-to-use)
> Move golangci-lint action to its own job

- README.md
* Current Build + integ test badge shows failing because it's looking up the old workflow name. This updates the name and aligns style with other badges
> Align build/integration test badge in ReadMe with updated gha workflow

- BUILD.md
- Dockerfile
- Makefile
- scripts/build-docker-images
- scripts/push-docker-images
- test/eks-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
- test/license-test/run-license-test.sh
- test/readme-test/run-readme-spellcheck
This ensures that the platform in the image manifest matches the platform of the binaries.
**Issue #, if available:** #584
* Modify the Dockerfile to pass through the docker buildx built-in arguments `TARGETOS` and `TARGETARCH`
* Remove support for `linux/arm` and `darwin/amd64` images, since they are not used in production workloads. Continuing to build them now would require using a different base image than `amazonlinux:2`, which does not support those architectures.
* Continue using the older build system for Windows images, since docker buildx in our current GitHub Actions configuration does not support Windows builds.
* Add a comment that explicitly annotating the image OS and architecture may not be necessary in the future
**Testing:**
Tested with GitHub …
> Add support for docker buildx on linux builds

- pkg/config/config.go
- pkg/node/node.go
**Issue #, if available:** 
https://github.com/aws/aws-node-termination-handler/issues/583
Currently, NTH pods can be scheduled on cordoned nodes that are being drained. The deployment can then get caught in a cycle of evicting its own pod(s) until the node is eventually terminated. To fix this behavior, we want to skip the pod that is running NTH while draining the node. We do this by passing in AdditionalFilters param within drain helper. AdditionalFilters are applied sequentially after base drain filters to exclude pods using custom logic. 
Passed e2e tests and tested it manually. 
> Filter nth pod while draining

- config/helm/aws-node-termination-handler/Chart.yaml
- scripts/prepare-for-release
🥑🤖 Auto-generated PR for v1.16.0 release. Updating release versions in repo.
> 🥑🤖 v1.16.0 release prep

- pkg/monitor/sqsevent/scheduled-change-event.go
In all other creations of `InterruptionEvent`, the `IsManaged` field is populated via `getNodeInfo`. This seems to have been missed in the work to support Scheduled Events. 
Without this, managed node checking doesn't work correctly for scheduled events.
> Add IsManaged nodeinfo field to scheduled events

- test/license-test/Dockerfile
- test/license-test/gen-license-report.sh
- test/readme-test/spellcheck-Dockerfile
- test/webhook-test-proxy/Dockerfile
**Issue #, if available:** ci/cd jobs using these Dockerfiles are pulling the latest go version (1.18) which deprecates `go get` functionality which leads to failures.
* aligns golang version with app
* follow best practices for installing a command using go install
* similar PR: https://github.com/aws/amazon-ec2-metadata-mock/pull/168 
> Update go & lib versions in Dockerfiles

- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/templates/servicemonitor.yaml
Signed-off-by: Victor Boissiere <victor.boissiere@qonto.com>
Fix issue on service monitor selector.
Current service monitor selector:
```yaml
selector:
matchLabels:
app.kubernetes.io/component: deployment
app.kubernetes.io/instance: aws-node-termination-handler
app.kubernetes.io/name: termination-handler
...
```
But the servicelabel  is
```yaml
apiVersion: v1
kind: Service
metadata:
labels:
app.kubernetes.io/component: aws-node-termination-handler <== here
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: termination-handler
...
```
Fix the issue by ensuring service monitor is target the same labels as the service
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …
> Fix service monitor selector

- .github/workflows/build-and-test.yaml
**Issue #, if available:** N/A `golangci` job failing due to timing out
**Description of changes:** increases timeout time of `golangci` job and hard-codes version instead of pulling in latest
> Update golangci action to increase timeout and hard-code version

- config/helm/aws-node-termination-handler/templates/_helpers.tpl
- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/templates/service.yaml
- config/helm/aws-node-termination-handler/templates/servicemonitor.yaml
This PR undoes the change made in #604 and fixes the actual issue I introduced in the chart refactor work.
> Fix Helm chart service labels

- README.md
- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/Chart.yaml
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/ec2-state-change-event.go
- pkg/monitor/sqsevent/rebalance-recommendation-event.go
- pkg/monitor/sqsevent/scheduled-change-event.go
- pkg/monitor/sqsevent/spot-itn-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/types.go
- pkg/node/node.go
**Issue description:**
At our organization we run Kubernetes on EC2 administered with kubeadm. We wanted to add NTH to allow spot instances to be used with proper cordon/draining logic. We use the queue processor mode which means that we receive events through SQS that is then mapped to the `NodeInfo` struct.
```
{
"InstanceID": "i-1234567890",
"IsManaged": true,
"Name": "ip-10.0.0.1.ap-northeast-2.compute.internal",
"Tags": {
"Name": "Kubernetes-worker",
"aws-node-termination-handler/managed": "true",
"aws:autoscaling:groupName": "Kubernetes-worker",
"example.com/environment": "testing",
"example.com/role": "Kubernetes-worker"
}
}
```
Now here is the problem: Our nodes have different hostnames from the default `ip-<ip>.<availability-zone>.compute.internal` format. It seems like the …
> Add option to fetch node name through Kubernetes node .spec.providerID in case custom names are used

- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
#619 TEST_NOTIFICATION event sent to newly added ASG lifecycle hook w/o Event Bridge triggers NTH panic
Added check for TEST_NOTIFICATION lifecycle transistion and logic to skip remaining processing rather than erroring.
> Ignore test notification events

- config/helm/aws-node-termination-handler/templates/deployment.yaml
Fixing properties to take the values from the values.yaml file and not to be hardcoded.
**Issue #, if available:** Values were hardcoded and when we are running helm upgrade command and sending the properties with --set command, is not setting the values. 
To test it, you can run the code in the documentation https://github.com/aws/aws-node-termination-handler:
helm upgrade --install aws-node-termination-handler \
--namespace kube-system \
--set enableSpotInterruptionDraining="true" \
--set enableRebalanceMonitoring="true" \
--set enableScheduledEventDraining="false" \
eks/aws-node-termination-handler
and you will see that the properties enableRebalanceMonitoring and enableSpotInterruptionDraining are not set. 
By submitting this pull request, I confirm that my …
> Update deployment.yaml file

- src/api/v1alpha1/terminator_logging.go
- src/api/v1alpha1/terminator_types.go
- src/api/v1alpha1/terminator_validation.go
- src/charts/aws-node-termination-handler-2/templates/node.k8s.aws_terminators.yaml
- src/cmd/controller/main.go
- src/pkg/event/noop.go
- src/pkg/node/getter.go
- src/pkg/terminator/adapter/nodegetter.go
- src/pkg/terminator/reconciler.go
- src/test/reconciliation_test.go
#556 Initial NTH v2 design proposal
Add `matchLabels` property to the Terminator spec.
NTH will take no action when an SQS message targets a node that does not have the requisite labels and values.
> add node label selector to Terminator

- src/api/v1alpha1/terminator_logging.go
- src/api/v1alpha1/terminator_types.go
- src/api/v1alpha1/terminator_validation.go
- src/charts/aws-node-termination-handler-2/templates/node.k8s.aws_terminators.yaml
- src/pkg/event/asgterminate/v1/handler.go
- src/pkg/event/asgterminate/v2/handler.go
- src/pkg/event/rebalancerecommendation/v0/handler.go
- src/pkg/event/scheduledchange/v1/handler.go
- src/pkg/event/spotinterruption/v1/handler.go
- src/pkg/event/statechange/v1/handler.go
- src/pkg/terminator/eventkind.go
- src/pkg/terminator/reconciler.go
- src/test/reconciliation_test.go
#556 Initial NTH v2 design proposal
Add `events` property to the Terminator spec which gives the option to instruct NTH to take no action, or only cordon nodes, when particular message types are received.
> add event action config to Terminator

- README.md
- pkg/monitor/sqsevent/scheduled-change-event.go
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/issues/550
**Description of changes:**  
- Modified the Event Bridge Rule for "MyK8sScheduledChangeRule" in README document to consider the detail-type for the AWS Health Events.
- Modified the conditions in "scheduled-change-event" file for checking service and event type category for AWS Health Events. Instead of returning an error, now it returns a warning message and deletes the messages that are not handled by NTH.
- For testing the changes, followed the below steps:
- Ran the e2e tests to check whether the modified changes are affecting any  other functionalities.
- Tried to send an AWS health event from different service other than EC2 from SQS service.
- Verified if the sent message has been deleted and …
> Fix AWS Health Event Bridge Rule

- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
#619 TEST_NOTIFICATION event sent to newly added ASG lifecycle hook w/o Event Bridge triggers NTH panic
Now also checks the `Event` field when determining whether the message is a test notification.
> ignore test notification Event

- src/api/v1alpha1/terminator_logging.go
- src/api/v1alpha1/terminator_types.go
- src/api/v1alpha1/terminator_validation.go
- src/charts/aws-node-termination-handler-2/templates/node.k8s.aws_terminators.yaml
- src/charts/aws-node-termination-handler-2/values.yaml
- src/cmd/controller/main.go
- src/pkg/event/asgterminate/v1/handler.go
- src/pkg/event/asgterminate/v2/handler.go
- src/pkg/event/noop.go
- src/pkg/event/rebalancerecommendation/v0/handler.go
- src/pkg/event/scheduledchange/v1/handler.go
- src/pkg/event/spotinterruption/v1/handler.go
- src/pkg/event/statechange/v1/handler.go
- src/pkg/terminator/adapter/webhookclient.go
- src/pkg/terminator/eventkind.go
- src/pkg/terminator/reconciler.go
- src/pkg/webhook/builder.go
- src/pkg/webhook/client.go
- src/pkg/webhook/notification.go
- src/pkg/webhook/request.go
- src/test/reconciliation_test.go
#556 Initial NTH v2 design proposal
Add `webhook` property to `Terminator` spec
> add webhook config to Terminator

- pkg/ec2metadata/ec2metadata.go
Sometimes IMDS may return non-200 status codes. We'd like to see the body of the response in those scenarios, in case there may be useful debugging data there.
Restructured the `GetMetadataInfo()` function to print response body with debug-level logging.
> Log IMDS response full text when status code not in 200 range

- cmd/node-termination-handler.go
- pkg/observability/opentelemetry.go
**Issue #, if available:** #650 
* add `node_event_id` label  to exported metrics
> feat(observability): add eventID to exposed metrics

- README.md
* Clarify that infrastructure setup steps need to be repeated per cluster in a multi-cluster environment.
* Minor rewording to clarify that only CloudFormation has templates at the moment.
> Update infra setup steps for multi-cluster

- pkg/monitor/scheduledevent/scheduled-event-monitor.go
- pkg/monitor/scheduledevent/scheduled-event-monitor_test.go
- pkg/test/helpers.go
**Issue #, if available:** #361
Update the IMDS mode handling of scheduled events to start immediately, the same as how queue processor mode currently works:
https://github.com/aws/aws-node-termination-handler/blob/814bccc507967f582867e065d4be916ab74fa5c0/pkg/monitor/sqsevent/scheduled-change-event.go#L100
We could probably remove  the date parsing altogether and get rid of `EndTime` (lines 90-101), since the SQS version does not set it at all and it does not appear to be used. But in the interest of making a small change, I'm leaving that code for now.
**Testing:**
Inside the NTH repo folder on my local machine, I ran the following commands:
```
kind create cluster --config test/k8s-local-cluster-test/kind-three-node-cluster.yaml
helm template …
```
> Handle scheduled events immediately in IMDS mode, the same as queue processor mode

- DEVELOPMENT.md
- Makefile
- charts/aws-node-termination-handler-2/templates/node.k8s.aws_terminators.yaml
- resources/eks-cluster.yaml.tmpl
- resources/queue-infrastructure.yaml
- resources/terminator.yaml.tmpl
- scripts/download-ko.sh
* `make apply` now uses the value of `CLUSTER_NAMESPACE` rather than a hardcoded namespace
* EventBridge rule name suffixes have been shorted to reduce likelihood of exceeding length limitation
* EKS cluster template now specifies Kuberentes v1.22
* `ko` is now installed from a pre-built binary rather than using `go install` to workaround a build issue in the ko project
* Dev guide now has instructions for verifying that an existing cluster has an IAM OIDC provider, and how to add one
* Dev guide now has steps to run `make help` and `make test`
* Dev guide now has an optional step to display all NTH v2 resources in the cluster
* Dev guide now has a list of tools used
* Dev guide steps and instructions have been revised and improved
* …
> update dev guide and resources

- README.md
**Issue:**
The Investigation if NTH is mandatory on EKS managed node groups took me few days. README.md is missing when it's recommended to deploy NTH - according to [issue](https://github.com/aws/aws-node-termination-handler/issues/186), it's pointless to deploy it on managed node groups. 
> chore(README): add hint about EKS managed node groups

- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
**Issue #595**
Remove `runAsUser` from `securityContext` map on Windows daemonset.
> Remove runAsUser in helm template for windows node

- .github/workflows/build-and-test.yaml
- Makefile
- scripts/build-binaries
- scripts/build-docker-images
- test/license-test/run-license-test.sh
**Description of changes:** Fix issues with linter job. fall back to go proxy (use direct first) so developers can start building immediately
**Related:**
* https://github.com/aws/aws-node-termination-handler/pull/672
* https://github.com/aws/amazon-ec2-instance-selector/commit/184e939e47216dfb0907b35030e3c12306fb1708
> CICD improvements: update golangci-lint & go proxy fallback

- README.md
- resources/eks-cluster.yaml.tmpl
- resources/infrastructure.yaml
Added a *Getting Started* section to README.md
> add 'getting started' section to README.md

- README.md
- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_internal_test.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
- test/e2e/asg-lifecycle-sqs-test
- test/e2e/ec2-state-change-sqs-test
- test/e2e/rebalance-recommendation-sqs-test
- test/e2e/scheduled-change-event-sqs-test
- test/e2e/spot-interruption-sqs-test
**Issue #, if available:** #654
* Replaced fields `check-asg-tag-before-draining` and `managed-asg-tag` with `check-tag-before-draining` and `managed-tag`, updated docs to mark them as deprecated, and removed them from charts
* Removed ASG api calls to fetch ASG info when determining whether a node should be managed by NTH.
* Fixed bug where the presence of the `managedAsgTag/managedTag` on an instance wouldn't be checked correctly before deferring to ASG lookup
> Filter managed non-ASG nodes by tag

- cmd/node-termination-handler.go
- pkg/logging/routing-integration_test.go
- pkg/logging/routing.go
- pkg/logging/routing_test.go
#667 Node Termination Handler only logs to stderr
Route messages of warning or higher to stderr, everything else to stdout.
> divide log output between stdout and stderr

- config/helm/aws-node-termination-handler/templates/daemonset.linux.yaml
- config/helm/aws-node-termination-handler/templates/daemonset.windows.yaml
Looks like this was (accidentally I presume) removed in #540 
I *think* helm changes are made here and not on the eks-charts repo?
If that's not correct I'm happy to open this there instead!
> helm: Apply extraEnv to daemonsets

- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
This fixes the logging so we log the MessageId, not a binary representation of the pointer. Otherwise we get messages like:
`2022/09/06 19:22:45 ERR error processing interruption events error="some interruption events for message Id 1100000000000000001111000101100011101000 could not be processed"`
> fix(sqs): log itn event messageid correctly

- pkg/monitor/sqsevent/sqs-monitor_test.go
**Issue #, if available:** #654
PR #669 removed calls to ASG APIs when checking for the "managed" tag on EC2 instances. Some of the unit tests were still testing that behavior, which is no longer necessary. This PR removes those functions.
A few of the unit tests do not need to set an `ASG` parameter at all, so I removed those lines entirely. In tests that do need the ASG parameter, I left it but passed in a default ASG mock object.
**Testing:**
Verified that unit tests pass after these changes. No changes made to functional production code, only unit tests.
> Remove unit test functions that mock ASG managed tag

- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
**Issue #, if available:** #682
We removed these flags in NTH release `v1.17.0`, but they are still supported for now. The Helm chart should allow both in the mean time.
If the Helm chart includes one of the deprecated flags at install time, NTH will issue a warning, such as the following ([source](https://github.com/aws/aws-node-termination-handler/blob/main/pkg/config/config.go#L223-L235)):
> Deprecated argument "managed-asg-tag" was provided. This argument will eventually be removed. Please switch to "managed-tag" instead.
> Add back deprecated flags for checking whether an instance is managed by NTH

- Makefile
- scripts/download-gum.sh
- scripts/prepare-for-release.sh
Add `scripts/prepare-for-release.sh` script which automates updating version numbers in documentation and the Helm chart, and opening a PR.
> add prepare-for-release.sh script

- Makefile
- scripts/build-and-push-images.sh
Add script that builds and pushes images to a repository.
> add build-and-push-images.sh script

- .github/workflows/release.yaml
Restrict `main` branch's release workflow to only trigger on tags `v1.*.*` to avoid unintended run when a `v2.*.*` tag is created.
> update release workflow trigger

- README.md
Make the difference between IMDS and Queue Processor modes easier to understand. Clarify the formatting, standardize the terminology, add links to AWS documentation, and simplify the table.
For a preview, see the rendered version on my branch: https://github.com/snay2/aws-node-termination-handler/blob/clarify-readme/README.md#major-features
> README: Clarify distinctions between IMDS and QP modes

- Makefile
- scripts/upload-resources-to-github.sh
Added script to upload contents of `resources/` to the latest release on GitHub.
> add upload-resources-to-github.com script

- DEVELOPMENT.md
- Makefile
- scripts/docker-login-ecr.sh
- scripts/sync-readme-to-ecr-public.sh
Add script that uploads the contents of README.md (up to the max allowed length) to the ECR public repos for the controller and webhook.
> add sync-readme-to-ecr-public.sh script

- .github/workflows/release.yml
- Makefile
> add release workflow

- charts/aws-node-termination-handler-2/Chart.yaml
🥑🤖 Auto-generated PR for v2.0.0-alpha release. Updating release versions in repo.
> 🥑🤖 v2.0.0-alpha release prep

- scripts/download-gh.sh
Path to the `gh` executable within the downloaded archive was incorrect.
Fixed path to `gh` executable within the downloaded archive.
> update gh path within downloaded archive

- scripts/sync-to-aws-eks-charts.sh
Script error due to attempting to move a file that didn't exist.
Add existence check before attempting to move the file.
> check that config file exists before move

- scripts/sync-to-aws-eks-charts.sh
Git user identity was not set in the sync-to-aws-eks-charts.sh script.
Set the user identity for the local repo.
> set git identity in sync-to-aws-eks-charts.sh

- cmd/node-termination-handler.go
- pkg/node/node.go
- pkg/node/node_internal_test.go
- pkg/node/node_test.go
- pkg/observability/k8s-events.go
**Issue #635:**
This is a followup of @dennisme 's PR https://github.com/aws/aws-node-termination-handler/pull/631 which in turn was a followup of @dthorsen 's work. All credits should go to them. The PR was closed for being stale with some pending questions and requests. In this PR I'll just try to satisfy these and try to get it finally merged.
I'll comment the code exactly where comments or requests were in the original PR, creating links to each original question and mentioning the author, and then I'll try to answer the question or satisfy the request.
I'm also adding some minor changes to the PR: deprecating `io/ioutil` in favor of `os`.
> feat: emit pod events on drain

- .github/workflows/release.yml
- scripts/sync-readme-to-ecr-public.sh
By default actions/checkout@v2 does not fetch git history.  Release script then fails when it attempts to look through the git history.
* Configure actions/checkout@v2 to fetch git history
* Silence unnecessary script output
> update release workflow

- pkg/observability/k8s-events.go
This PR enriches Kubernetes events when running in SQS mode by adding annotations to such events, so they can later be used to get information about the node involved in the event, create filters, etc. Similar to what was done in #411 
I have decided to add almost the same annotations the events in IMDS mode have, but I'd like some thoughts here because most of the information is gathered from node labels so we could simply attach all node labels as tags instead, or even do the two approaches simultaneously.
The only annotation I'm not adding here is `instance-life-cycle` because that's something that can be easily obtained from the IMDS endpoint but it's not present in the Kubernetes `Node` object, so it would have to be fetched from the AWS API instead …
> chore: add annotations to events in SQS mode

- README.md
After a recent discussion, I noticed that the docs are confusingly worded about how and why to use ASG tags. This PR clears up that wording. It also fixes a broken link to the AWS documentation.
> Clarify wording about using ASG tags. Fix broken docs link.

- pkg/config/config_internal_test.go
- pkg/config/config_test.go
A testing cleanup.
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
```
By submitting this pull …
> test: use `T.Setenv` to set env vars in tests

- README.md
- cmd/node-termination-handler.go
- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_test.go
Fixes https://github.com/aws/aws-node-termination-handler/issues/732
When IMDSv2 is enabled and aws-note-termination-handler is ran inside a container accessing IMDSv2 is not possible due to the IMDSv2 HTTP endpoint's default hop limit of 1. This makes the process exit.
Completely disables the communication with the IMDS endpoint when in SQS queue mode.
> Completely ignore Instance Metadata when in SQS Queue mode.

- pkg/event/asgterminate/v1/parser.go
- pkg/event/asgterminate/v2/parser.go
- pkg/event/rebalancerecommendation/v0/parser.go
- pkg/event/scheduledchange/v1/parser.go
- pkg/event/spotinterruption/v1/parser.go
- pkg/event/statechange/v1/parser.go
- resources/queue-infrastructure.yaml
Incoming event versions do not match expected schema versions.
For now, remove the event version checks.  We may re-add the checks in the future.
> remove event schema version checks

- cmd/node-termination-handler.go
N/A
The documentation states:
> The Queue Processor Mode does not allow for fine-grained configuration of which events are handled through helm configuration keys.
The `.Values.enableScheduledEventDraining` helm configuration key does control one aspect of NTH in Queue Processor mode: whether upon startup it attempts to uncordon the node it is running on.
This appears to be a bug. There is no logical reason for NTH to uncordon the node it is running on when not in IMDS mode.
> Don't try to uncordon on startup in Queue Processor mode

- pkg/config/config.go
- pkg/node/node.go
None
When draining a node, NTH skips evicting itself. It incorrectly skipped evicting pods in other namespaces that happened to have the same name.
> Don't skip evicting pods with same name but in different namespace

- pkg/node/node.go
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/issues/685
- As per the PR comments, modified log statement from Error to Warning as this doesn't affect any expected outcome.
- This error is mainly due to mismatch between Node labels as per the code and we already have a fallback mechanism.
-  Ran tests locally and all tests passed.
> Error log fix

- README.md
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/issues/418
- Removed link initially as it is creating confusion if AZ rebalance recommendation is only for EC2 Spot Instances.
- Modified the ASG AZ rebalance link for better understanding of AZ rebalancing.
> AZ Rebalance Recommendation Document Fix

- README.md
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/issues/536
Added some information related to ASG w/ capacity-rebalance option in README as per PR discussions.
> Added detailed ASG information in README

- pkg/monitor/sqsevent/spot-itn-event.go
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/issues/757
We are returning the EventBridge event start time, in our case when instance received spot interruption. Current time is returned when we cannot parse the time in the specific format and we get a warning message that `Unable to parse time as RFC3339 from event, using current time instead`, we cannot hardcode the time for spot interruption as it might take 2 or minutes to terminate. Modified the Spot Interruption event message to make it more clear.
> Modified Spot ITN message

- THIRD_PARTY_LICENSES
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/pull/763
In the mentioned PR, the license test failed due to missing third party licenses `go-colorable` and `go-isatty`. Included these licenses in `THIRD_PARTY_LICENSES`. 
> Included required third party licenses

- .github/workflows/build-and-test.yaml
Current linter version (golangci-lint-action v3.2.0, golangci-lint v1.45.2) raises what appear to be false positives.
* Updated golangci-lint-action to latest (v3.4.0)
* Updated golangci-lint to latest (v1.51.1)
> Update workflow linter version

- cmd/node-termination-handler.go
- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/templates/deployment.yaml
- config/helm/aws-node-termination-handler/values.yaml
- pkg/config/config.go
- test/e2e/rebalance-recommendation-sqs-node-not-found-test
- test/k8s-local-cluster-test/run-test
#787 Delete SQS message if node is not found
Added Helm value to enable deletion of SQS message if the targeted node is not found. Default value is `false`.
> optionally delete sqs message when node not found

- pkg/ec2metadata/ec2metadata.go
- pkg/ec2metadata/ec2metadata_internal_test.go
- pkg/ec2metadata/ec2metadata_test.go
- pkg/uptime/common.go
- pkg/uptime/common_test.go
- pkg/webhook/webhook.go
- pkg/webhook/webhook_test.go
Lint Eastwood checks are failing in NTH Build and Test due to the deprecated `io/ioutil` package used in our code.
```
Error: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details.  (staticcheck)
```
Modified all the files that are using `io/ioutil` package and used `io` and  `os` packages to get the same result.
> Removed io/ioutil package as it is deprecated and used io and os package

- Makefile
- scripts/generate-k8s-yaml
- scripts/upload-resources-to-github
#799 v1.25+ Compatible Release Resource Artifacts
Updated script to generate two sets of resources for k8s 1.24 and 1.25
> generate resource files for k8s 1.25

- .github/workflows/build-and-test.yaml
- README.md
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
Test suite still uses k8s versions that are no longer supported by EKS.
Remove older k8s versions from test version lists.
> update k8s test versions

- pkg/observability/opentelemetry.go
https://github.com/aws/aws-node-termination-handler/issues/374
- zeros metrics when registered
```
> ec2-metadata-mock -d 100000 &
> go run cmd/node-termination-handler.go -enable-prometheus-server --dry-run --node-name test --metadata-url http://localhost:1338 -enable-scheduled-event-draining=false
> curl http://localhost:9092/metrics
actions_node_total{otel_scope_name="aws.node.termination.handler",otel_scope_version=""} 0
events_error_total{otel_scope_name="aws.node.termination.handler",otel_scope_version=""} 0
...
```
```
> ec2-metadata-mock &
> go run cmd/node-termination-handler.go -enable-prometheus-server --dry-run --node-name test --metadata-url http://localhost:1338 -enable-scheduled-event-draining=false
> curl …
```
> Metric zero

- .github/workflows/build-and-test.yaml
- .github/workflows/release.yaml
- Dockerfile
- Dockerfile.windows
- README.md
- go.mod
- test/readme-test/spellcheck-Dockerfile
- test/webhook-test-proxy/Dockerfile
- test/webhook-test-proxy/Dockerfile.windows
> up go to 1.20

- Makefile
Release script fails on the extra double quotes - https://github.com/aws/aws-node-termination-handler/actions/runs/5291868437/jobs/9619737977#step:4:660
> remove extra double quotes

- scripts/upload-resources-to-github
Fix release script to upload binaries to Github only once. 
```
$ ./upload-resources-to-github 
Uploading release assets for release id 'TEST' to Github
1. *
2. individual-resources.tar
3. all-resources.yaml
4. individual-resources-queue-processor.tar
5. all-resources-queue-processor.yaml
----
$./upload-resources-to-github -s "-test"
Uploading release assets for release id 'TEST' to Github
1. *
2. individual-resources-test.tar
3. all-resources-test.yaml
4. individual-resources-queue-processor-test.tar
5. all-resources-queue-processor-test.yaml
---
$./upload-resources-to-github -s "-test" -k
Uploading release assets for release id 'TEST' to Github
1. individual-resources-test.tar
2. all-resources-test.yaml
3. individual-resources-queue-processor-test.tar
4. …
```
> fix release script to upload binaries once

- test/eks-cluster-test/cluster-spec.yaml
Updated Kubernetes version in `cluster-spec.yaml` , we are using older version leading to test failures. Kubernetes supported versions start from `1.22`
> Fixed kubernetes version in test file

- README.md
- docs/cfn-template.yaml
* Enable SQS managed server-side encryption in CloudFormation template
> enable SQS server-side encryption

- BUILD.md
- README.md
While going over the installation process for a test setup I noticed some small QoL changes.
* Remove the leading `$ ` for code blocks, makes them functional when copy pasting them to a terminal
* Remove invalid `"SqsManagedSseEnabled": true` from the queue attributes
* When executing `sqs create-queue` this returns the error: `Invalid type for parameter Attributes.SqsManagedSseEnabled, value: True, type: <class 'bool'>, valid types: <class 'str'>`
* According to https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-sse-existing-queue.html encryption is enabled by default anyway. Also details on SQS encryption are outlined below the code block.
By submitting this pull request, I confirm that my …
> docs: Cleanup installation process for Queue Processor

- pkg/node/node.go
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/issues/857
`fetchKubernetesNode` function is used in almost all the functions in `node.go` to  fetch the Kubernetes node. As per the existing functionality, `fetchKubernetesNode` function checks the FQDN, modified existing logic to include matching both the short names such as `ip-xxx` as well as FQDN `ip-xxx.xxx.internal`. 
> Allow short node name matching

- README.md
#823 
Created a matrix/table that details the compatibility of recent NTH release with recent Kubernetes versions. A green checkmark indicates that a NTH release is compatible with a K8s version, and a red X indicates incompatibility. This table is located in the ReadMe.md file in the "Major Features" section. 
> Created the Kubernetes Compatibility Table

- test/eks-cluster-test/cluster-spec.yaml
- test/eks-cluster-test/provision-cluster
- test/eks-cluster-test/run-test
Fixing error in E2E tests where test node was being improperly sourced. Updated EKS cluster configuration with updated version and the provisioning of spot nodes.
> E2E tests bug fix 

- README.md
- config/helm/aws-node-termination-handler/README.md
- pkg/observability/opentelemetry.go
- test/e2e/prometheus-metrics-test
#925 #665 
NTH's prometheus metric, "actions_node", has a high cardinality due to its "node_name" and "node_event_id" labels. This causes each event to be tracked as its own time-series, which can cause a large amount of memory to be  consumed over time. 
A new metric, "actions", has been created without the "node_name" and "node_event_id" labels, greatly reducing the cardinality of the metric. The "actions_node" metric has been deprecated and the "actions" metric is recommended for use instead. The "actions_node" metric is planned for removal in later releases.
> Prometheus metric leak

- Makefile
- scripts/install-amazon-ecr-credential-helper
#954 
Same error message was reported in https://github.com/aws/aws-cli/issues/5636 which is caused by https://github.com/danieljoos/wincred/issues/18 which is because of a limitation in a Windows API.
Use [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) instead of pre-installed WinCred credentials helper.
> fix ECR credentials for Windows release workflow

- README.md
* Add columns for k8s v1.28 and v1.27
* Undo mistaken change of NTH "v1.20" to "v1.21"
> update k8s compatibility table

- Makefile
* Invoke bash directly to run `scripts/install-amazon-ecr-credential-helper` on Windows
> invoke bash directly on Windows

- pkg/monitor/sqsevent/asg-lifecycle-event.go
The description was probably copied from the old interruption event in #940, I was pretty confused when I read the logs.
> Fix misleading launch event log message

- pkg/monitor/sqsevent/asg-lifecycle-event.go
- Fixes #990
This PR reverts the removal of the lifecycle hook completions for ASG lifecycle events.
> fix: Reverted the removal of the lifecycle hook completion

- Makefile
We are currently having issues adding windows binaries to release assets. We are planning to mitigate this as soon as possible. Due to these issues, we are unable to push helm charts to ecr-public causing inconvenience to customers. Temporarily removing uploading resources for windows to have smooth release process.
> Temporarily removed uploading windows binaries to release assets

- Makefile
- scripts/upload-resources-to-github-windows.ps1
- Added a new PowerShell script to support adding windows release assets to GitHub.
- Reverted the removal of uploading windows binaries to GitHub, we will not experience any further issues adding windows release assets to latest release.
I tested in my local fork to view the output. Here is the link for the test release:
https://github.com/LikithaVemulapalli/aws-node-termination-handler/releases/tag/v1.112.0
> Added new PowerShell script for windows support

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/node/node.go
**Issue #, if available:** https://github.com/aws/aws-node-termination-handler/issues/1017
**Description of changes:** Exposes the configuration `use_apiserver_cache`, which sets `ResourceVersion: "0"` when listing pods on a node.
> Allow using kube-apiserver cache for pod list requests

- pkg/monitor/sqsevent/sqs-monitor.go
> SQS Monitor should handle all kinds of InvalidInstanceID errors

- Makefile
Adding windows binaries to release assets is failing when we are doing a new NTH release. We fixed this earlier and able to view windows binaries uploaded successfully in our local forks. We will fix this in next release.
> Removing adding windows binaries to release assets

- .github/workflows/release.yaml
N/A
- Synchronize the linux and windows release process to avoid a timing issue where the manifest gets overwritten. 
> synchronize the linux and windows release process to avoid overwriting the manifest

- cmd/node-termination-handler.go
I identified an issue with the polling logic in the `handleRebootUncordon` function within the IMDS mode of NTH. Currently, the polling continues regardless of whether the uncordon checks and requests succeed, because the wrapped function always returns `false`. This behavior results in repeated retries until the context timeout is reached, ultimately causing a misleading "context deadline exceeded" error.
Here is the error message that is always displayed:
```
2024/08/29 13:42:42 WRN All retries failed, unable to complete the uncordon after reboot workflow error="context deadline exceeded"
```
I’ve modified the wrapper function to return `true` when `handleRebootUncordon` completes successfully without errors. This ensures that polling stops once all calls to …
> Incorrect polling logic in handleRebootUncordon for Scheduled Event Draining

- pkg/observability/opentelemetry.go
- pkg/observability/opentelemetry_test.go
Fix prometheus port (#1078) and add unit test for opentelemetry (#1088)
**Issue #, if available: 
#1078
#1088
- When enablePrometheusServer config is false, we will not open the port
- Add unit test for pkg/observability/opentelemetry.go file
> Fix prometheus port (#1078) and add unit test for opentelemetry (#1088)

- pkg/ec2metadata/ec2metadata.go
- test/e2e/emit-events-test
- test/e2e/prometheus-metrics-test
- test/e2e/webhook-test
- Add custom service client when perform e2e test
- Make sure AEMM is up before NTH
- Fix validation in prometheus-metrics-test
> Fix e2e tests failure in action of build and test

- cmd/node-termination-handler.go
- pkg/monitor/sqsevent/sqs-retryer.go
- pkg/monitor/sqsevent/sqs-retryer_test.go
#717
- Add sqs client retryer
- Add sqs client retryer unit test
> Add sqs client retryer

- .github/workflows/build-and-test.yaml
- Makefile
- scripts/generate-k8s-yaml
- test/k8s-compatibility-test/run-k8s-compatibility-test.sh
- test/k8s-local-cluster-test/provision-cluster
- test/k8s-local-cluster-test/run-test
- Deprecate old k8s version
Kubernetes Version: 1.31
Test in local by `make compatibility-test`
> Deprecate old k8s version

- pkg/node/node.go
- pkg/node/node_test.go
#1097
- Add filtering before DeleteOrEvictPods
Kubernetes Version: 1.31
Set `use-apiserver-cache: true` and `emit-kubernetes-events: true` then toggle the `ignore-daemon-sets` flag to test protect daemonset pods or not.
> Add filtering before DeleteOrEvictPods

- pkg/monitor/sqsevent/asg-lifecycle-event.go
- pkg/monitor/sqsevent/ec2-state-change-event.go
- pkg/monitor/sqsevent/rebalance-recommendation-event.go
- pkg/monitor/sqsevent/scheduled-change-event.go
- pkg/monitor/sqsevent/spot-itn-event.go
- pkg/monitor/sqsevent/sqs-monitor.go
- pkg/monitor/sqsevent/sqs-monitor_internal_test.go
- pkg/monitor/sqsevent/sqs-monitor_test.go
- pkg/monitor/types.go
- pkg/webhook/webhook.go
Feature - would like to expose the InstanceType also in the webhook notifications
Changes - Updated getNodeInfo to return the InstanceType 
> Add SQS InterruptionEvent.InstanceType

- README.md
Issue #1101 
Updated README to clarify ambiguity between lifecycle hook support in Queue Processor mode and lifecycle state change support in IMDS mode. 
NA
> Update README.md with more details on lifecycle state in IMDS mode

- cmd/node-termination-handler.go
- pkg/ec2helper/ec2helper.go
- pkg/ec2helper/ec2helper_test.go
- pkg/node/node.go
- pkg/node/node_test.go
- pkg/observability/opentelemetry.go
- pkg/observability/opentelemetry_test.go
- test/e2e/prometheus-metrics-sqs-test
Close #785 
- Count nodes/instances being tracked. Eg:
`k get node` return 5
`aws ec2 describe-instances` return 2
**Identify 3 nodes no longer under NTH control**
> Prometheus add nodes gauge for SQS mode 

- config/helm/aws-node-termination-handler/README.md
- config/helm/aws-node-termination-handler/values.yaml
#1135
Add helm default value (-1) for heartbeatInterval and heartbeatUntil
Kubernetes Version: 1.31
Helm upgrade dryrun commend
> Fix helm default val for heartbeat flags

- .github/workflows/build-and-test.yaml
- .github/workflows/release.yaml
- .github/workflows/stale.yml
We are using deprecated versions in our workflows causing Github Actions workflow failures.
- Modified the `actions/cache` versions from v2 to v4 as per recommendation in official notice.
- Modified `ubuntu` versions as well in workflows as the current versions will be deprecated by March end.
> Modified cache and ubuntu versions to resolve the build failures

- pkg/node/node.go
#1148
Fix log level in drain helper by passing custom loggers.
Ref:
- `evictPods` and `fmt.Fprintf` in [pkg/drain/drain.go](https://github.com/kubernetes/kubectl/blob/fec9d5b3d5b1c3addf8cebd3c2437257ea5e4332/pkg/drain/drain.go#L268)
- `Fprintf` in [src/fmt/print.go](https://github.com/golang/go/blob/master/src/fmt/print.go#L222-L225)
Kubernetes Version: 1.32
Test by:
- e2e test
- deploy NTH by private ECR image; trigger spot interruption; validate the log messages
Prev:
```
INF Draining the node
??? evicting pod kube-system/ebs-csi-controller-xxx
??? error when evicting pods/"ebs-csi-controller-xxx" -n "kube-system" (will retry after 5s): Cannot evict pod as it …
```
> Fix log level in drain helper

- pkg/node/node.go
Add `node_name` property to `Draining the node` message
The log message without the context doesn't really help, for example when using a logging system like Graylog/ELK and you want to filter for everything related to that node.
Kubernetes Version: 1.32
> Add node_name to `Draining the node` message

- .github/workflows/build-and-test.yaml
- .github/workflows/release.yaml
- Makefile
- README.md
- config/helm/aws-node-termination-handler/Chart.yaml
- test/eks-cluster-test/cluster-spec.yaml
🥑🤖 Auto-generated PR for v1.25.2 release. Updating release versions in repo.
> 🥑🤖 v1.25.2 release prep

- README.md
**Issue #, if available:** [1182](https://github.com/aws/aws-node-termination-handler/issues/1182)
- Updated readme note and added deprecation notice link. 
Environment (Linux / Windows): 
Kubernetes Version: 
> Add windows 2019 deprecation link in readme
